// The Cloudflare Worker that fronts the R2 share bucket.
//
// One tiny Worker does both sides:
//   - PUT  /<username>/<slug>  — bearer-gated by TWO principals (not a fallback):
//       1. Static WRITE_TOKEN (BYO Cloudflare) — checked first when the presented
//          bearer equals env.WRITE_TOKEN. owner = env.SHARE_NAMESPACE or the
//          path's first segment.
//       2. Phoenix bearer — otherwise GET ${env.PHOENIX_ID_BASE}/api/v1/auth/me
//          with that bearer → {userId,email}; 401 if absent/invalid.
//          customMetadata.owner = userId (stable). The path's first segment MUST
//          equal handleFromEmail(email) (the public handle, e.g. muqsitnawaz),
//          so one user cannot write another's prefix (403 namespace mismatch).
//          A __handles/<handle> claim binds the handle to the first userId that
//          writes it; a different userId gets 409 handle taken.
//     A managed deployment sets PHOENIX_ID_BASE; BYO sets WRITE_TOKEN; the
//     platform endpoint may set both. Fail loud (401) when neither authenticates.
//     Writes the body to R2 via the BUCKET binding, storing visibility
//     (public|unlisted|me|org), owner, org_domain (org only), an optional
//     expires-at, plus provenance (agent/session/host/repo/date), a label, and
//     any `--meta` entries in object metadata. me/org require a Phoenix
//     identity (BYO WRITE_TOKEN cannot publish them). org from a public inbox
//     domain is 400. Overwriting an existing slug first copies the current
//     object to <slug>/rev-<ts>-<rand> (revision history) unless
//     x-share-no-revision is set.
//   - GET  /<username>/<slug>  — public|unlisted are anonymous; me requires the
//     Phoenix owner, org requires a same-domain Phoenix identity (Bearer, then
//     HMAC cookie, then phoenix_ticket). Unauthenticated me/org 302s to
//     Phoenix login (or 401 JSON if PHOENIX_ID_BASE is unset). 410s (and lazily
//     deletes) once its expiry has passed. A bucket lifecycle rule is the durable
//     sweeper; this is the immediate gate.
//   - GET  /<username>/<slug>?revisions=json — machine-readable history of the
//     retained prior versions under that slug, newest first.
//   - GET  /<username>         — public gallery of that user's shares (HTML).
//   - GET  /<username>?format=json — public machine-readable listing of that user's
//     ACTIVE shares (`agents artifacts share list`). Same single-segment path as the HTML
//     gallery and gated on the SAME "does <username>/ hold any object" check, so it
//     only intercepts a genuine namespace — a legacy flat slug with ?format=json
//     still serves its real content, never a fake empty listing.
//   - GET  /<slug>             — backward-compat flat slug (legacy shares before
//     per-user namespaces).
//
// Emitted as a string, so it compiles into `dist/**` and ships with no
// package.json#files change. `provision.ts` uploads
// this verbatim as an ES-module Worker with a BUCKET (R2) binding + a WRITE_TOKEN secret.

/**
 * Render the Worker source. Pure — the R2 binding + token are wired at deploy time.
 *
 * The literal below still spells the CLI `agents share` in its provenance comment,
 * its root response, and its gallery title, even though the command is now
 * `agents artifacts share` (RUSH-2580). That is deliberate: `hashWorkerScript` of
 * this exact text is what `shareTemplateStatus` compares a provisioned endpoint's
 * recorded `templateHash` against, so editing ANY byte here marks every already-
 * deployed endpoint `outdated` — which makes `agents artifacts share list` refuse
 * until its owner re-runs `agents artifacts share update`. Cosmetic renames are not
 * worth that; change this text only alongside a real Worker behavior change.
 */
export function renderWorkerScript(): string {
  return `// GENERATED by agents-cli agents share setup — do not edit here; edit
// src/lib/share/worker-template.ts and re-run setup.
export const hooks = {
  verifyPhoenixToken: defaultVerifyPhoenixToken,
};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));

    if (!path) {
      return new Response('agents share — POST is not it; PUT /<username>/<slug> to publish, GET /<username>/<slug> to view.', {
        status: 200, headers: { 'content-type': 'text/plain; charset=utf-8' },
      });
    }

    const firstSeg = path.split('/').filter(Boolean)[0] || '';
    if ((request.method === 'GET' || request.method === 'HEAD') && firstSeg.startsWith('__')) {
      return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
    }

    if (request.method === 'PUT') {
      const auth = await authorizeWrite(request, env);
      if (auth.error) return auth.error;
      const vis = normalizeVisibility(request.headers.get('x-share-visibility'));
      if (vis.error) return vis.error;
      const visibility = vis.value;
      if (visibility === 'me' || visibility === 'org') {
        const phoenixBase = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
        if (auth.kind !== 'phoenix' || !phoenixBase) {
          return json({ error: 'visibility me/org requires Phoenix identity' }, 400);
        }
        if (visibility === 'org') {
          const domain = emailDomain(auth.email);
          if (!domain) return json({ error: 'org visibility requires a verified email domain' }, 400);
          if (PUBLIC_INBOX_DOMAINS.indexOf(domain) !== -1) {
            return json({ error: 'org visibility cannot use a public email domain', domain: domain }, 400);
          }
        }
      }
      const segments = path.split('/').filter(Boolean);
      if (auth.kind === 'phoenix') {
        const expected = phoenixHandle(auth);
        if (!expected || segments[0] !== expected) {
          return json({ error: 'namespace mismatch', owner: expected }, 403);
        }
        const claimed = await claimHandle(env.BUCKET, expected, auth.owner);
        if (claimed.error) return claimed.error;
      }
      const expiresAt = request.headers.get('x-share-expires-at') || '';
      // 'unlisted' hides the page from the public gallery + JSON listing while
      // keeping the direct URL world-readable (capability URL, not secret).
      // me/org are also hidden from gallery/listing; GET is identity-gated
      // and always sends X-Robots-Tag: noindex (same as unlisted).
      const contentType = request.headers.get('content-type') || 'text/html; charset=utf-8';
      // Provenance (RUSH-2683): captured client-side from the exec env/git/clock,
      // never invented here — a header is simply absent when the CLI had nothing
      // to say. --meta entries ride one JSON header; reserved keys are stripped
      // from that JSON UNCONDITIONALLY (not just overwritten when a provenance
      // header happens to be present) so a same-named x-share-meta entry can
      // never smuggle through on a publish that carries no agent/session/host/
      // repo/date at all — e.g. a human publishing outside an agent session, or
      // outside a git checkout.
      const agent = request.headers.get('x-share-agent') || '';
      const session = request.headers.get('x-share-session') || '';
      const host = request.headers.get('x-share-host') || '';
      const repo = request.headers.get('x-share-repo') || '';
      const date = request.headers.get('x-share-date') || '';
      const label = request.headers.get('x-share-label') || '';
      const labelSource = request.headers.get('x-share-label-source') || '';
      let extraMeta = {};
      const metaHeader = request.headers.get('x-share-meta');
      if (metaHeader) {
        try {
          const parsed = JSON.parse(metaHeader);
          if (parsed && typeof parsed === 'object') extraMeta = parsed;
        } catch {
          // malformed --meta header — ignore rather than fail the whole publish
        }
      }
      const customMetadata = { ...extraMeta };
      // Strip every reserved key UNCONDITIONALLY before re-applying the real
      // provenance below — an if(value)-guarded overwrite alone leaves a
      // same-named --meta entry in place whenever the real header is absent.
      for (const reservedKey of RESERVED_METADATA_KEYS) {
        delete customMetadata[reservedKey];
      }
      if (expiresAt) customMetadata['expires-at'] = expiresAt;
      customMetadata['visibility'] = visibility;
      const owner =
        auth.kind === 'phoenix'
          ? auth.owner
          : (env.SHARE_NAMESPACE || segments[0] || 'byo');
      if (owner) customMetadata['owner'] = owner;
      if (visibility === 'org') customMetadata['org_domain'] = emailDomain(auth.email);
      if (agent) customMetadata['agent'] = agent;
      if (session) customMetadata['session'] = session;
      if (host) customMetadata['host'] = host;
      if (repo) customMetadata['repo'] = repo;
      if (date) customMetadata['date'] = date;
      if (label) customMetadata['label'] = label;
      if (labelSource) customMetadata['label-source'] = labelSource;

      // Revision retention (RUSH-2683): R2 has no native object versioning, so a
      // republish over an EXISTING key first copies the current object to
      // <key>/rev-<ts>-<rand> before the canonical key is overwritten. Default
      // keep-all; --no-revision (x-share-no-revision) skips it. The random
      // suffix guards against two rapid overwrites of the same slug colliding on
      // the millisecond, and against a slug whose canonical key already sits 3+
      // segments deep (an unsupported shape outside the CLI) landing on the same
      // literal revision key.
      const noRevision = !!request.headers.get('x-share-no-revision');
      if (!noRevision) {
        const existing = await env.BUCKET.get(path);
        if (existing) {
          const existingHeaders = new Headers();
          if (typeof existing.writeHttpMetadata === 'function') existing.writeHttpMetadata(existingHeaders);
          const existingContentType = existingHeaders.get('content-type');
          const revKey = path + '/rev-' + Date.now() + '-' + Math.random().toString(36).slice(2, 8);
          await env.BUCKET.put(revKey, existing.body, {
            httpMetadata: existingContentType ? { contentType: existingContentType } : undefined,
            customMetadata: existing.customMetadata || {},
          });
        }
      }

      await env.BUCKET.put(path, request.body, {
        httpMetadata: { contentType },
        customMetadata,
      });
      return json({ ok: true, url: url.origin + '/' + path, expiresAt: expiresAt || null, unlisted: visibility === 'unlisted', visibility }, 200);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      // Single-segment path may be a user gallery/listing OR a legacy flat slug.
      // The disambiguator is whether the <seg>/ prefix holds any object: only a
      // genuine per-user namespace does. BOTH the HTML gallery and the
      // machine-readable listing gate on it, so ?format=json on a legacy flat
      // slug (an object stored at the bare key, before per-user namespaces) does
      // NOT hijack it into a fake empty listing — it falls through to the object
      // GET below and serves its real content, exactly as before.
      const segments = path.split('/').filter(Boolean);
      if (segments.length === 1) {
        const list = await env.BUCKET.list({ prefix: segments[0] + '/', limit: 1 });
        const isNamespace = list.objects && list.objects.length > 0;
        if (isNamespace) {
          return url.searchParams.get('format') === 'json'
            ? renderListing(env.BUCKET, url.origin, segments[0], request.method)
            : renderGallery(env.BUCKET, url.origin, segments[0], request.method);
        }
        // Not a namespace: fall through. A legacy flat-slug object resolves to its
        // real content; anything else 404s (an empty/nonexistent namespace, which
        // agents share list reads as "nothing published" via the template-hash
        // signal rather than a missing route).
      }

      // Revision history for one canonical <user>/<slug> key (RUSH-2683). Checked
      // before the plain object GET below so the query param routes even though
      // the canonical key itself resolves to a real object. me/org use the same
      // identity gate as the page GET — listing session/host/repo on an unauthed
      // ?revisions=json must not leak that the page exists.
      if (segments.length === 2 && url.searchParams.get('revisions') === 'json') {
        const canonical = await env.BUCKET.get(path);
        if (canonical) {
          const denied = await gateRestrictedGet(request, env, url, canonical);
          if (denied) return denied;
        }
        return renderRevisions(
          env.BUCKET,
          url.origin,
          path,
          request.method,
          canonical && isIdentityGated((canonical.customMetadata && canonical.customMetadata.visibility) || 'public'),
        );
      }

      const obj = await env.BUCKET.get(path);
      if (!obj) return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
      const expiresAt = obj.customMetadata && obj.customMetadata['expires-at'];
      if (expiresAt && Date.now() > Date.parse(expiresAt)) {
        await env.BUCKET.delete(path);
        return new Response('gone — this link has expired', { status: 410, headers: { 'content-type': 'text/plain' } });
      }
      const denied = await gateRestrictedGet(request, env, url, obj);
      if (denied) return denied;
      const visibility = (obj.customMetadata && obj.customMetadata.visibility) || 'public';
      const headers = new Headers();
      obj.writeHttpMetadata(headers);
      headers.set('etag', obj.httpEtag);
      if (!headers.has('content-type')) headers.set('content-type', 'text/html; charset=utf-8');
      if (visibility === 'me' || visibility === 'org') {
        headers.set('cache-control', 'private, no-store');
        headers.set('X-Robots-Tag', 'noindex');
      } else {
        headers.set('cache-control', 'public, max-age=60');
        if (visibility === 'unlisted') headers.set('X-Robots-Tag', 'noindex');
      }
      if (request.method === 'HEAD') return new Response(null, { status: 200, headers });
      const ctype = headers.get('content-type') || '';
      // ?raw ALWAYS returns the stored bytes untouched — the escape hatch for
      // <img src>, OG crawlers, iframes, and anyone embedding the asset. The
      // media element inside the viewer below points back at ?raw for exactly this.
      const wantsRaw = url.searchParams.get('raw') != null;
      if (!wantsRaw) {
        // HTML pages get the attribution bar injected at serve time (who shared
        // it, what made it, when, and — the point — a visual VISIBILITY cue), all
        // from stamped metadata. The body changes, so the R2 etag no longer
        // matches — drop it rather than serve a lying validator.
        if (ctype.indexOf('text/html') !== -1) {
          const rawHtml = await obj.text();
          const withBar = injectAttributionBar(rawHtml, obj.customMetadata || {}, firstSeg);
          headers.delete('etag');
          return new Response(withBar, { status: 200, headers });
        }
        // A BROWSER navigating directly to a non-HTML asset (image / video /
        // audio / pdf) gets a lightweight viewer page carrying the same bar. A
        // non-browser fetch (Accept without text/html — <img>, OG crawler, curl)
        // falls through to the raw bytes, so embedding is never broken.
        const kind = viewableAssetKind(ctype);
        if (kind && acceptsHtml(request)) {
          const viewer = renderAssetViewer(url.pathname, kind, obj.customMetadata || {}, firstSeg);
          const vheaders = new Headers(headers);
          vheaders.set('content-type', 'text/html; charset=utf-8');
          vheaders.delete('etag');
          return new Response(viewer, { status: 200, headers: vheaders });
        }
      }
      return new Response(obj.body, { status: 200, headers });
    }

    if (request.method === 'DELETE') {
      const auth = await authorizeWrite(request, env);
      if (auth.error) return auth.error;
      if (auth.kind === 'phoenix') {
        const handle = phoenixHandle(auth);
        const uid = sanitizeNamespace(auth.owner);
        const delSegments = path.split('/').filter(Boolean);
        // Handle is the public namespace; userId prefix is still deletable so
        // P1 UUID-namespaced objects the same account published can be taken down.
        // A colliding local-part (same handle, different userId) must not be
        // able to DELETE the claimant's pages — consult the claim the same way PUT does.
        if (delSegments[0] && delSegments[0] === uid) {
          // own leftover UUID prefix
        } else if (delSegments[0] && delSegments[0] === handle) {
          const owned = await assertHandleOwner(env.BUCKET, handle, auth.owner);
          if (owned.error) return owned.error;
        } else {
          return json({ error: 'namespace mismatch', owner: handle || uid }, 403);
        }
      }
      await env.BUCKET.delete(path);
      return json({ ok: true, deleted: path }, 200);
    }

    return new Response('method not allowed', { status: 405 });
  },
};

// A canonical share object's key is exactly 2 segments (<user>/<slug>, or the
// sibling <user>/<slug>.png OG cover). A retained revision lives a 3rd segment
// deeper (<user>/<slug>/rev-<ts>-<rand>) — history, not a page in its own
// right, so every gallery/listing view hides it. A raw external PUT to an
// already-3-segment-deep path is treated the same way for the same reason:
// there is no ambiguity to resolve, and the CLI never produces such a key.
function isRevisionKey(key) {
  return key.split('/').length > 2;
}

async function renderGallery(bucket, origin, user, method) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: user + '/', limit: 1000, cursor, include: ['customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  const activeObjects = objects.filter(o => {
    if (isRevisionKey(o.key)) return false;
    if (o.key.endsWith('.png')) return false;
    // Unlisted / me / org pages are reachable by direct URL only — never on the gallery.
    if (isHiddenFromGallery(o.customMetadata && o.customMetadata.visibility)) return false;
    const expiresAt = o.customMetadata && o.customMetadata['expires-at'];
    return !(expiresAt && Date.now() > Date.parse(expiresAt));
  });
  const items = activeObjects.map(o => {
    const slug = o.key.slice(o.key.indexOf('/') + 1);
    const url = origin + '/' + o.key;
    const label = (o.customMetadata && o.customMetadata['label']) || '';
    const agent = (o.customMetadata && o.customMetadata['agent']) || '';
    return { slug, url, updated: o.uploaded, label, agent };
  });

  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8' } });
  }

  const html =
    '<!doctype html><html><head>' +
    '<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<title>' + escapeHtml(user) + ' — agents share</title>' +
    '<style>' +
    'body{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:720px;margin:48px auto;padding:0 24px;color:#111;background:#fafafa}' +
    'h1{font-size:28px;margin-bottom:8px}a{color:#0a0a0a;text-decoration:none;border-bottom:1px solid #999}' +
    'a:hover{border-color:#111}ul{list-style:none;padding:0}li{margin:16px 0}' +
    '.slug{font-weight:600}.title{font-weight:600}.meta{color:#666;font-size:14px}' +
    '</style></head><body>' +
    '<h1>@' + escapeHtml(user) + '</h1>' +
    '<p class="meta">' + items.length + ' shared ' + (items.length === 1 ? 'page' : 'pages') + '</p>' +
    '<ul>' +
    items.map(i =>
      '<li>' +
      (i.label ? '<span class="title">' + escapeHtml(i.label) + '</span><br>' : '') +
      '<a class="slug" href="' + escapeHtml(i.url) + '">' + escapeHtml(i.slug) + '</a>' +
      '<br><span class="meta">' + new Date(i.updated).toISOString().slice(0, 10) +
      (i.agent ? ' · ' + escapeHtml(i.agent) : '') + '</span></li>'
    ).join('') +
    '</ul></body></html>';
  return new Response(html, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=60' } });
}

async function renderListing(bucket, origin, user, method) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: user + '/', limit: 1000, cursor, include: ['httpMetadata', 'customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  // Revisions never appear as their own listing row, but they count toward
  // their canonical object's revisionCount.
  const revisionCounts = {};
  for (const o of objects) {
    if (!isRevisionKey(o.key)) continue;
    const canonicalKey = o.key.split('/').slice(0, 2).join('/');
    revisionCounts[canonicalKey] = (revisionCounts[canonicalKey] || 0) + 1;
  }

  const now = Date.now();
  const items = objects
    .filter(o => {
      // Mirror the gallery: hide revisions, sibling .png OG covers, expired
      // pages, and unlisted/me/org pages — the listing is the machine-readable public surface.
      if (isRevisionKey(o.key)) return false;
      if (o.key.endsWith('.png')) return false;
      if (isHiddenFromGallery(o.customMetadata && o.customMetadata.visibility)) return false;
      const expiresAt = o.customMetadata && o.customMetadata['expires-at'];
      return !(expiresAt && now > Date.parse(expiresAt));
    })
    .map(o => ({
      slug: o.key.slice(o.key.indexOf('/') + 1),
      url: origin + '/' + o.key,
      size: typeof o.size === 'number' ? o.size : 0,
      contentType: (o.httpMetadata && o.httpMetadata.contentType) || null,
      publishedAt: new Date(o.uploaded).toISOString(),
      expiresAt: (o.customMetadata && o.customMetadata['expires-at']) || null,
      label: (o.customMetadata && o.customMetadata['label']) || null,
      agent: (o.customMetadata && o.customMetadata['agent']) || null,
      session: (o.customMetadata && o.customMetadata['session']) || null,
      host: (o.customMetadata && o.customMetadata['host']) || null,
      repo: (o.customMetadata && o.customMetadata['repo']) || null,
      revisionCount: revisionCounts[o.key] || 0,
      meta: extraMetaOf(o.customMetadata),
    }));
  // Newest first, so the human table and any script reads the freshest share top.
  items.sort((a, b) => (a.publishedAt < b.publishedAt ? 1 : a.publishedAt > b.publishedAt ? -1 : 0));

  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } });
  }
  return new Response(JSON.stringify({ user, count: items.length, objects: items }), {
    status: 200,
    headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=30' },
  });
}

async function renderRevisions(bucket, origin, key, method, identityGated) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: key + '/rev-', limit: 1000, cursor, include: ['httpMetadata', 'customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  const items = objects.map(o => ({
    key: o.key,
    url: origin + '/' + o.key,
    size: typeof o.size === 'number' ? o.size : 0,
    contentType: (o.httpMetadata && o.httpMetadata.contentType) || null,
    uploadedAt: new Date(o.uploaded).toISOString(),
    expiresAt: (o.customMetadata && o.customMetadata['expires-at']) || null,
    label: (o.customMetadata && o.customMetadata['label']) || null,
    agent: (o.customMetadata && o.customMetadata['agent']) || null,
    session: (o.customMetadata && o.customMetadata['session']) || null,
    host: (o.customMetadata && o.customMetadata['host']) || null,
    repo: (o.customMetadata && o.customMetadata['repo']) || null,
    meta: extraMetaOf(o.customMetadata),
  }));
  // Newest first — the most recently replaced version leads.
  items.sort((a, b) => (a.uploadedAt < b.uploadedAt ? 1 : a.uploadedAt > b.uploadedAt ? -1 : 0));

  const cacheHeaders = identityGated
    ? { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'private, no-store', 'X-Robots-Tag': 'noindex' }
    : { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=30' };
  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: cacheHeaders });
  }
  return new Response(JSON.stringify({ key, count: items.length, revisions: items }), {
    status: 200,
    headers: cacheHeaders,
  });
}

// The customMetadata keys the CLI sets automatically (provenance + label) —
// never a real \`--meta key=value\` entry (the CLI rejects a colliding key
// before it ever reaches this Worker; see RESERVED_META_KEYS in publish.ts).
// One list, reused both to strip a same-named --meta collision on write and
// to split arbitrary --meta entries back out on read.
var RESERVED_METADATA_KEYS = ['expires-at', 'visibility', 'owner', 'org_domain', 'agent', 'session', 'host', 'repo', 'date', 'label', 'label-source'];
var PUBLIC_INBOX_DOMAINS = ['gmail.com', 'googlemail.com', 'outlook.com', 'hotmail.com', 'live.com', 'icloud.com', 'me.com'];
var SHARE_COOKIE = '__Host-phoenix_share';
var SHARE_COOKIE_MAX_AGE = 604800;

// Everything in customMetadata that ISN'T one of the reserved provenance/label
// keys above — i.e. the caller's own \`--meta key=value\` entries. Surfaced on
// every read route (listing, revisions) so a value stored with \`--meta
// kind=plan --meta ticket=RUSH-2683\` is actually visible again, not just
// write-only (RUSH-2683 review fix).
function extraMetaOf(customMetadata) {
  var out = {};
  if (!customMetadata) return out;
  for (var k in customMetadata) {
    if (RESERVED_METADATA_KEYS.indexOf(k) === -1) out[k] = customMetadata[k];
  }
  return out;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// The attribution bar: a slim strip prepended to every served HTML page that
// makes the object's stamped metadata visible — who shared it, what made it,
// when, and (the whole point) a color-coded VISIBILITY cue Google-Drive style.
// All values come from customMetadata; nothing new is stamped at publish time,
// so this is a pure Worker change deployable with 'agents artifacts share update'.
var VIS_ICON = {
  me: '<svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="11" width="16" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/></svg>',
  org: '<svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 21h18M6 21V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v17M14 9h4a1 1 0 0 1 1 1v11"/></svg>',
  unlisted: '<svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1"/><path d="M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1"/></svg>',
  public: '<svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg>',
};

function visibilityChip(visibility, orgDomain) {
  if (visibility === 'me') return { icon: VIS_ICON.me, label: 'Only you', color: '#f59e0b' };
  if (visibility === 'org') return { icon: VIS_ICON.org, label: 'Anyone at ' + escapeHtml(orgDomain || 'your organization'), color: '#5b9dff' };
  if (visibility === 'unlisted') return { icon: VIS_ICON.unlisted, label: 'Unlisted', color: '#9aa0a6' };
  return { icon: VIS_ICON.public, label: 'Public', color: '#30a46c' };
}

function renderAttributionBar(meta, handle) {
  var cm = meta || {};
  var chip = visibilityChip(cm.visibility || 'public', cm.org_domain);
  var left = '';
  // The handle is already the public URL namespace, so surfacing it leaks nothing new.
  if (handle) left += 'Shared by <strong>' + escapeHtml(handle) + '</strong>';
  if (cm.agent) left += (left ? '<span class="ash-dot">·</span>' : '') + 'Made with ' + escapeHtml(cm.agent);
  var right = '<span class="ash-chip" style="color:' + chip.color + ';border-color:' + chip.color + '66">' + chip.icon + '<span>' + chip.label + '</span></span>';
  if (cm.date) right += '<span class="ash-date">' + escapeHtml(cm.date) + '</span>';
  // The load-bearing background + base colour ride an INLINE style so the host
  // page's own CSS can never wash the bar out (inline beats a page stylesheet);
  // the rest is a namespaced style block with !important on every colour so a
  // broad page rule (span selector to black, etc.) cannot make the text vanish.
  // FIXED, full-viewport-width chrome (not sticky-inside-body — that inherited the
  // page's max-width/margins and rendered as a floating box). html padding-top
  // pushes the whole page down by the bar's height; flex-wrap:nowrap + ellipsis on
  // the left keeps the bar exactly one line tall so the push height stays correct.
  return '<div class="agents-share-bar" role="contentinfo" aria-label="Sharing details" ' +
    'style="background:#0b0b0c !important;color:#e8e8e8 !important">' +
    '<style>' +
    'html{padding-top:38px !important}' +
    '.agents-share-bar{all:initial;position:fixed !important;top:0 !important;left:0 !important;right:0 !important;width:100% !important;z-index:2147483647 !important;box-sizing:border-box;display:flex !important;align-items:center;gap:12px;flex-wrap:nowrap;' +
    'padding:8px 16px !important;background:#0b0b0c !important;color:#e8e8e8 !important;border-bottom:1px solid #23232a !important;box-shadow:0 1px 3px rgba(0,0,0,.35) !important;' +
    'font:13px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,system-ui,sans-serif !important}' +
    '.agents-share-bar *{box-sizing:border-box;font-family:inherit}' +
    '.agents-share-bar .ash-left{flex:1 1 auto;min-width:0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;color:#cfd3d9 !important}' +
    '.agents-share-bar strong{color:#fff !important;font-weight:600}' +
    '.agents-share-bar .ash-dot{opacity:.4;margin:0 4px}' +
    '.agents-share-bar .ash-right{flex:none;display:flex;align-items:center;gap:12px}' +
    '.agents-share-bar .ash-date{color:#9096a0 !important}' +
    '.agents-share-bar .ash-chip{display:inline-flex;align-items:center;gap:6px;padding:3px 10px;border-radius:999px;border:1px solid;font-weight:600;font-size:12px;white-space:nowrap}' +
    '.agents-share-bar .ash-chip svg{flex:none;vertical-align:middle}' +
    '</style>' +
    '<span class="ash-left">' + left + '</span>' +
    '<span class="ash-right">' + right + '</span>' +
    '</div>';
}

function injectAttributionBar(html, meta, handle) {
  var bar = renderAttributionBar(meta, handle);
  var m = /<body[^>]*>/i.exec(html);
  if (m) {
    var at = m.index + m[0].length;
    return html.slice(0, at) + bar + html.slice(at);
  }
  return bar + html;
}

function acceptsHtml(request) {
  return (request.headers.get('accept') || '').indexOf('text/html') !== -1;
}

// Assets we can embed in a viewer page. Everything else (JSON, .txt, arbitrary
// downloads) is served raw — there is nothing useful to wrap it in.
function viewableAssetKind(contentType) {
  var ct = (contentType || '').toLowerCase();
  if (ct.indexOf('image/') === 0) return 'image';
  if (ct.indexOf('video/') === 0) return 'video';
  if (ct.indexOf('audio/') === 0) return 'audio';
  if (ct.indexOf('application/pdf') === 0) return 'pdf';
  return '';
}

// A minimal dark viewer page: the attribution bar on top, the asset centered
// below. The media element points back at THIS url with ?raw so it loads the
// stored bytes (not the viewer recursively) — and that ?raw fetch re-runs the
// same me/org gate, so a private asset stays private inside its own viewer.
function renderAssetViewer(pathname, kind, meta, handle) {
  var rawUrl = escapeHtml(pathname + '?raw=1');
  var name = '';
  try { name = decodeURIComponent(pathname.split('/').pop() || 'file'); } catch (e) { name = pathname.split('/').pop() || 'file'; }
  var bar = renderAttributionBar(meta, handle);
  var media = '';
  if (kind === 'image') media = '<img src="' + rawUrl + '" alt="' + escapeHtml(name) + '">';
  else if (kind === 'video') media = '<video src="' + rawUrl + '" controls playsinline></video>';
  else if (kind === 'audio') media = '<audio src="' + rawUrl + '" controls></audio>';
  else if (kind === 'pdf') media = '<iframe src="' + rawUrl + '" title="' + escapeHtml(name) + '"></iframe>';
  return '<!doctype html><html><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">' +
    '<title>' + escapeHtml(name) + '</title>' +
    '<style>html,body{margin:0;background:#0f0f11}' +
    'body{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:16px;box-sizing:border-box}' +
    '.ashv{max-width:100%;max-height:calc(100vh - 90px);display:flex;align-items:center;justify-content:center}' +
    '.ashv img,.ashv video{max-width:100%;max-height:calc(100vh - 90px);display:block;border-radius:8px;box-shadow:0 10px 40px rgba(0,0,0,.5)}' +
    '.ashv audio{width:min(90vw,560px)}' +
    '.ashv iframe{width:min(94vw,1000px);height:calc(100vh - 90px);border:0;border-radius:8px;background:#fff}' +
    '</style></head><body>' + bar + '<div class="ashv">' + media + '</div></body></html>';
}

function json(body, status) {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

// Length-independent constant-time-ish compare (Workers has no timingSafeEqual).
function safeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  const la = a.length, lb = b.length;
  let out = la ^ lb;
  for (let i = 0; i < la; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i % lb || 0);
  return out === 0 && la === lb;
}

// URL-safety, not collision-resistance. Two values that differ only in
// case/punctuation share a prefix.
function sanitizeNamespace(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

// Public handle: email local-part, plus-tag stripped. Must match CLI handleFromEmail.
function handleFromEmail(email) {
  if (!email) return '';
  const local = String(email).split('@')[0] || '';
  const beforePlus = local.split('+')[0] || local;
  return sanitizeNamespace(beforePlus);
}

function phoenixHandle(auth) {
  return handleFromEmail(auth.email) || sanitizeNamespace(auth.owner);
}

// First writer of a handle owns it. Later PUTs from the same userId are fine;
// a different userId whose email local-part collides gets 409, not a silent overwrite.
async function assertHandleOwner(bucket, handle, userId) {
  // The __handles/<handle> claim object is the authoritative first-writer record
  // of ownership. When it exists it decides ownership OUTRIGHT: the recorded
  // userId may write, anyone else is refused. Consult it FIRST — a stray page
  // under the namespace stamped with a different owner (e.g. a BYO WRITE_TOKEN
  // publish, which stamps owner = SHARE_NAMESPACE rather than a userId, or a page
  // published under the same human's earlier userId before a re-auth) must not
  // lock the rightful claim holder out of their own handle (PHNX-3291).
  const key = '__handles/' + handle;
  const existing = await bucket.get(key);
  if (existing) {
    const claimed = existing.customMetadata && existing.customMetadata.userId;
    if (claimed && claimed !== userId) {
      return { error: json({ error: 'handle taken', handle: handle }, 409) };
    }
    return {};
  }
  // No claim object yet — fall back to the page-owner scan so a colliding email
  // local-part cannot PUT/DELETE another account's objects in the window before
  // the claim exists. (claimHandle writes the claim on the first Phoenix PUT.)
  // Only a DIFFERENT Phoenix userId blocks: a BYO WRITE_TOKEN publish stamps
  // owner = the namespace (=== handle) rather than a userId, so it is not a rival
  // identity and must not lock the handle's first Phoenix claimant out (PHNX-3291).
  const list = await bucket.list({ prefix: handle + '/', include: ['customMetadata'] });
  for (const o of list.objects || []) {
    const owner = o.customMetadata && o.customMetadata.owner;
    if (owner && owner !== userId && owner !== handle) {
      return { error: json({ error: 'handle taken', handle: handle }, 409) };
    }
  }
  return {};
}

async function claimHandle(bucket, handle, userId) {
  const owned = await assertHandleOwner(bucket, handle, userId);
  if (owned.error) return owned;
  const key = '__handles/' + handle;
  // Write (or rewrite) so a same-user republish resets object Age against the
  // bucket's 366-day lifecycle — otherwise the claim can expire while pages stay live.
  await bucket.put(key, JSON.stringify({ userId: userId }), {
    httpMetadata: { contentType: 'application/json' },
    customMetadata: { userId: userId, visibility: 'unlisted' },
  });
  return {};
}

function normalizeVisibility(raw) {
  const v = (raw || '').trim().toLowerCase();
  if (!v || v === 'public') return { value: 'public' };
  if (v === 'unlisted' || v === 'me' || v === 'org') return { value: v };
  return { error: json({ error: 'visibility must be public, unlisted, me, or org' }, 400) };
}

function emailDomain(email) {
  if (!email) return '';
  const at = String(email).lastIndexOf('@');
  if (at < 0) return '';
  return String(email).slice(at + 1).toLowerCase();
}

function isHiddenFromGallery(visibility) {
  return visibility === 'unlisted' || visibility === 'me' || visibility === 'org';
}

function isIdentityGated(visibility) {
  return visibility === 'me' || visibility === 'org';
}

async function gateRestrictedGet(request, env, url, obj) {
  const visibility = (obj.customMetadata && obj.customMetadata.visibility) || 'public';
  if (!isIdentityGated(visibility)) return null;
  const viewer = await resolveViewer(request, env, url);
  if (viewer.redirect) return viewer.redirect;
  if (viewer.error) return viewer.error;
  if (!viewer.identity) return bounceToLogin(url, env);
  if (!viewerMayRead(visibility, obj.customMetadata, viewer.identity)) {
    return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
  }
  return null;
}

function viewerMayRead(visibility, meta, identity) {
  if (visibility === 'me') {
    const owner = meta && meta.owner;
    return !!owner && owner === identity.userId;
  }
  if (visibility === 'org') {
    const stamped = meta && meta.org_domain;
    if (!stamped) return false;
    return emailDomain(identity.email) === String(stamped).toLowerCase();
  }
  return true;
}

function bounceToLogin(url, env) {
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base) return json({ error: 'phoenix login is not configured' }, 401);
  return new Response(null, {
    status: 302,
    headers: { Location: base + '/login?return=' + encodeURIComponent(url.toString()) },
  });
}

function readCookie(request, name) {
  const header = request.headers.get('Cookie') || '';
  const parts = header.split(';');
  for (let i = 0; i < parts.length; i++) {
    const p = parts[i];
    const eq = p.indexOf('=');
    if (eq < 0) continue;
    if (p.slice(0, eq).trim() === name) return p.slice(eq + 1).trim();
  }
  return '';
}

function toB64Url(s) {
  const bytes = new TextEncoder().encode(s);
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin).replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=+$/, '');
}

function fromB64Url(s) {
  const pad = s.length % 4 === 0 ? '' : '='.repeat(4 - (s.length % 4));
  const b64 = s.replace(/-/g, '+').replace(/_/g, '/') + pad;
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}

function bufToHex(buf) {
  return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('');
}

async function hmacHex(secret, data) {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(data));
  return bufToHex(sig);
}

async function signShareCookie(identity, env) {
  const secret = typeof env.WRITE_TOKEN === 'string' ? env.WRITE_TOKEN : '';
  if (!secret) return '';
  const exp = Math.floor(Date.now() / 1000) + SHARE_COOKIE_MAX_AGE;
  const payload = identity.userId + '|' + (identity.email || '') + '|' + exp;
  const sig = await hmacHex(secret, payload);
  const value = toB64Url(payload) + '.' + sig;
  return SHARE_COOKIE + '=' + value + '; HttpOnly; Secure; Path=/; SameSite=Lax; Max-Age=' + SHARE_COOKIE_MAX_AGE;
}

async function identityFromCookie(request, env) {
  const secret = typeof env.WRITE_TOKEN === 'string' ? env.WRITE_TOKEN : '';
  if (!secret) return null;
  const raw = readCookie(request, SHARE_COOKIE);
  if (!raw) return null;
  const dot = raw.lastIndexOf('.');
  if (dot < 1) return null;
  let payload;
  try {
    payload = fromB64Url(raw.slice(0, dot));
  } catch {
    return null;
  }
  const sig = raw.slice(dot + 1);
  const expected = await hmacHex(secret, payload);
  if (!safeEqual(sig, expected)) return null;
  const first = payload.indexOf('|');
  const last = payload.lastIndexOf('|');
  if (first < 0 || last <= first) return null;
  const userId = payload.slice(0, first);
  const email = payload.slice(first + 1, last);
  const cookieExp = Number(payload.slice(last + 1));
  if (!userId || !Number.isFinite(cookieExp) || Math.floor(Date.now() / 1000) > cookieExp) return null;
  return { userId: userId, email: email };
}

async function redeemTicket(ticket, env) {
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base || !ticket) return null;
  let res;
  try {
    res = await fetch(base + '/api/v1/auth/ticket', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ ticket: ticket }),
    });
  } catch {
    return null;
  }
  if (!res.ok) return null;
  let body;
  try {
    body = await res.json();
  } catch {
    return null;
  }
  if (!body || typeof body.userId !== 'string' || !body.userId) return null;
  return { userId: body.userId, email: typeof body.email === 'string' ? body.email : '' };
}

async function resolveViewer(request, env, url) {
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (claims && typeof claims.userId === 'string' && claims.userId) {
    return { identity: { userId: claims.userId, email: typeof claims.email === 'string' ? claims.email : '' } };
  }
  const cookieId = await identityFromCookie(request, env);
  if (cookieId) return { identity: cookieId };
  const ticket = url.searchParams.get('phoenix_ticket');
  if (!ticket) return {};
  const redeemed = await redeemTicket(ticket, env);
  if (!redeemed) return { error: json({ error: 'invalid ticket' }, 401) };
  const cookie = await signShareCookie(redeemed, env);
  if (!cookie) return { error: json({ error: 'phoenix login is not configured' }, 401) };
  url.searchParams.delete('phoenix_ticket');
  const headers = new Headers();
  headers.set('Location', url.toString());
  headers.append('Set-Cookie', cookie);
  return { redirect: new Response(null, { status: 302, headers: headers }) };
}

async function defaultVerifyPhoenixToken(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return null;
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base) return null;
  let res;
  try {
    res = await fetch(base + '/api/v1/auth/me', {
      method: 'GET',
      headers: { Authorization: 'Bearer ' + presented },
    });
  } catch {
    return null;
  }
  if (!res.ok) return null;
  let body;
  try {
    body = await res.json();
  } catch {
    return null;
  }
  if (!body || typeof body.userId !== 'string' || !body.userId) return null;
  return { userId: body.userId, email: typeof body.email === 'string' ? body.email : '' };
}

// Two legitimate principals: WRITE_TOKEN equality first (admin/BYO), otherwise
// the bearer is a Phoenix token and we verify it. 401 when neither authenticates.
async function authorizeWrite(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return { error: json({ error: 'unauthorized' }, 401) };
  if (env.WRITE_TOKEN && safeEqual(presented, env.WRITE_TOKEN)) {
    return { kind: 'byo', owner: env.SHARE_NAMESPACE || 'byo' };
  }
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (claims && typeof claims.userId === 'string' && claims.userId) {
    return { kind: 'phoenix', owner: claims.userId, email: typeof claims.email === 'string' ? claims.email : '' };
  }
  return { error: json({ error: 'unauthorized' }, 401) };
}
`;
}
