// The Cloudflare Worker that fronts the R2 share bucket.
//
// One tiny Worker does both sides:
//   - PUT  /<username>/<slug>  — bearer-gated by TWO principals (not a fallback):
//       1. Static WRITE_TOKEN (BYO Cloudflare) — checked first when the presented
//          bearer equals env.WRITE_TOKEN. owner = env.SHARE_NAMESPACE or the
//          path's first segment.
//       2. Phoenix bearer — otherwise GET ${env.PHOENIX_ID_BASE}/api/v1/auth/me
//          with that bearer → {userId,email}; 401 if absent/invalid.
//          customMetadata.owner = userId (stable). The path's first segment MUST
//          equal handleFromEmail(email) (the public handle, e.g. muqsitnawaz),
//          so one user cannot write another's prefix (403 namespace mismatch).
//          A __handles/<handle> claim binds the handle to the first userId that
//          writes it; a different userId gets 409 handle taken.
//     A managed deployment sets PHOENIX_ID_BASE; BYO sets WRITE_TOKEN; the
//     platform endpoint may set both. Fail loud (401) when neither authenticates.
//     Writes the body to R2 via the BUCKET binding, storing visibility
//     (public|unlisted; org → 400 in P1), owner, an optional expires-at, plus
//     provenance (agent/session/host/repo/date), a label, and any `--meta`
//     entries in object metadata. Overwriting an existing slug first copies the
//     current object to <slug>/rev-<ts>-<rand> (revision history) unless
//     x-share-no-revision is set.
//   - GET  /<username>/<slug>  — public; streams the object from R2, 410s (and lazily
//     deletes) once its expiry has passed. A bucket lifecycle rule is the durable
//     sweeper; this is the immediate gate.
//   - GET  /<username>/<slug>?revisions=json — machine-readable history of the
//     retained prior versions under that slug, newest first.
//   - GET  /<username>         — public gallery of that user's shares (HTML).
//   - GET  /<username>?format=json — public machine-readable listing of that user's
//     ACTIVE shares (`agents artifacts share list`). Same single-segment path as the HTML
//     gallery and gated on the SAME "does <username>/ hold any object" check, so it
//     only intercepts a genuine namespace — a legacy flat slug with ?format=json
//     still serves its real content, never a fake empty listing.
//   - GET  /<slug>             — backward-compat flat slug (legacy shares before
//     per-user namespaces).
//
// Emitted as a string, so it compiles into `dist/**` and ships with no
// package.json#files change. `provision.ts` uploads
// this verbatim as an ES-module Worker with a BUCKET (R2) binding + a WRITE_TOKEN secret.

/**
 * Render the Worker source. Pure — the R2 binding + token are wired at deploy time.
 *
 * The literal below still spells the CLI `agents share` in its provenance comment,
 * its root response, and its gallery title, even though the command is now
 * `agents artifacts share` (RUSH-2580). That is deliberate: `hashWorkerScript` of
 * this exact text is what `shareTemplateStatus` compares a provisioned endpoint's
 * recorded `templateHash` against, so editing ANY byte here marks every already-
 * deployed endpoint `outdated` — which makes `agents artifacts share list` refuse
 * until its owner re-runs `agents artifacts share update`. Cosmetic renames are not
 * worth that; change this text only alongside a real Worker behavior change.
 */
export function renderWorkerScript(): string {
  return `// GENERATED by agents-cli agents share setup — do not edit here; edit
// src/lib/share/worker-template.ts and re-run setup.
export const hooks = {
  verifyPhoenixToken: defaultVerifyPhoenixToken,
};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));

    if (!path) {
      return new Response('agents share — POST is not it; PUT /<username>/<slug> to publish, GET /<username>/<slug> to view.', {
        status: 200, headers: { 'content-type': 'text/plain; charset=utf-8' },
      });
    }

    const firstSeg = path.split('/').filter(Boolean)[0] || '';
    if ((request.method === 'GET' || request.method === 'HEAD') && firstSeg.startsWith('__')) {
      return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
    }

    if (request.method === 'PUT') {
      const auth = await authorizeWrite(request, env);
      if (auth.error) return auth.error;
      const vis = normalizeVisibility(request.headers.get('x-share-visibility'));
      if (vis.error) return vis.error;
      const visibility = vis.value;
      const segments = path.split('/').filter(Boolean);
      if (auth.kind === 'phoenix') {
        const expected = phoenixHandle(auth);
        if (!expected || segments[0] !== expected) {
          return json({ error: 'namespace mismatch', owner: expected }, 403);
        }
        const claimed = await claimHandle(env.BUCKET, expected, auth.owner);
        if (claimed.error) return claimed.error;
      }
      const expiresAt = request.headers.get('x-share-expires-at') || '';
      // 'unlisted' hides the page from the public gallery + JSON listing while
      // keeping the direct URL world-readable (capability URL, not secret).
      // GET also sends X-Robots-Tag: noindex for unlisted objects.
      const contentType = request.headers.get('content-type') || 'text/html; charset=utf-8';
      // Provenance (RUSH-2683): captured client-side from the exec env/git/clock,
      // never invented here — a header is simply absent when the CLI had nothing
      // to say. --meta entries ride one JSON header; reserved keys are stripped
      // from that JSON UNCONDITIONALLY (not just overwritten when a provenance
      // header happens to be present) so a same-named x-share-meta entry can
      // never smuggle through on a publish that carries no agent/session/host/
      // repo/date at all — e.g. a human publishing outside an agent session, or
      // outside a git checkout.
      const agent = request.headers.get('x-share-agent') || '';
      const session = request.headers.get('x-share-session') || '';
      const host = request.headers.get('x-share-host') || '';
      const repo = request.headers.get('x-share-repo') || '';
      const date = request.headers.get('x-share-date') || '';
      const label = request.headers.get('x-share-label') || '';
      const labelSource = request.headers.get('x-share-label-source') || '';
      let extraMeta = {};
      const metaHeader = request.headers.get('x-share-meta');
      if (metaHeader) {
        try {
          const parsed = JSON.parse(metaHeader);
          if (parsed && typeof parsed === 'object') extraMeta = parsed;
        } catch {
          // malformed --meta header — ignore rather than fail the whole publish
        }
      }
      const customMetadata = { ...extraMeta };
      // Strip every reserved key UNCONDITIONALLY before re-applying the real
      // provenance below — an if(value)-guarded overwrite alone leaves a
      // same-named --meta entry in place whenever the real header is absent.
      for (const reservedKey of RESERVED_METADATA_KEYS) {
        delete customMetadata[reservedKey];
      }
      if (expiresAt) customMetadata['expires-at'] = expiresAt;
      customMetadata['visibility'] = visibility;
      const owner =
        auth.kind === 'phoenix'
          ? auth.owner
          : (env.SHARE_NAMESPACE || segments[0] || 'byo');
      if (owner) customMetadata['owner'] = owner;
      if (agent) customMetadata['agent'] = agent;
      if (session) customMetadata['session'] = session;
      if (host) customMetadata['host'] = host;
      if (repo) customMetadata['repo'] = repo;
      if (date) customMetadata['date'] = date;
      if (label) customMetadata['label'] = label;
      if (labelSource) customMetadata['label-source'] = labelSource;

      // Revision retention (RUSH-2683): R2 has no native object versioning, so a
      // republish over an EXISTING key first copies the current object to
      // <key>/rev-<ts>-<rand> before the canonical key is overwritten. Default
      // keep-all; --no-revision (x-share-no-revision) skips it. The random
      // suffix guards against two rapid overwrites of the same slug colliding on
      // the millisecond, and against a slug whose canonical key already sits 3+
      // segments deep (an unsupported shape outside the CLI) landing on the same
      // literal revision key.
      const noRevision = !!request.headers.get('x-share-no-revision');
      if (!noRevision) {
        const existing = await env.BUCKET.get(path);
        if (existing) {
          const existingHeaders = new Headers();
          if (typeof existing.writeHttpMetadata === 'function') existing.writeHttpMetadata(existingHeaders);
          const existingContentType = existingHeaders.get('content-type');
          const revKey = path + '/rev-' + Date.now() + '-' + Math.random().toString(36).slice(2, 8);
          await env.BUCKET.put(revKey, existing.body, {
            httpMetadata: existingContentType ? { contentType: existingContentType } : undefined,
            customMetadata: existing.customMetadata || {},
          });
        }
      }

      await env.BUCKET.put(path, request.body, {
        httpMetadata: { contentType },
        customMetadata,
      });
      return json({ ok: true, url: url.origin + '/' + path, expiresAt: expiresAt || null, unlisted: visibility === 'unlisted', visibility }, 200);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      // Single-segment path may be a user gallery/listing OR a legacy flat slug.
      // The disambiguator is whether the <seg>/ prefix holds any object: only a
      // genuine per-user namespace does. BOTH the HTML gallery and the
      // machine-readable listing gate on it, so ?format=json on a legacy flat
      // slug (an object stored at the bare key, before per-user namespaces) does
      // NOT hijack it into a fake empty listing — it falls through to the object
      // GET below and serves its real content, exactly as before.
      const segments = path.split('/').filter(Boolean);
      if (segments.length === 1) {
        const list = await env.BUCKET.list({ prefix: segments[0] + '/', limit: 1 });
        const isNamespace = list.objects && list.objects.length > 0;
        if (isNamespace) {
          return url.searchParams.get('format') === 'json'
            ? renderListing(env.BUCKET, url.origin, segments[0], request.method)
            : renderGallery(env.BUCKET, url.origin, segments[0], request.method);
        }
        // Not a namespace: fall through. A legacy flat-slug object resolves to its
        // real content; anything else 404s (an empty/nonexistent namespace, which
        // agents share list reads as "nothing published" via the template-hash
        // signal rather than a missing route).
      }

      // Revision history for one canonical <user>/<slug> key (RUSH-2683). Checked
      // before the plain object GET below so the query param routes even though
      // the canonical key itself resolves to a real object.
      if (segments.length === 2 && url.searchParams.get('revisions') === 'json') {
        return renderRevisions(env.BUCKET, url.origin, path, request.method);
      }

      const obj = await env.BUCKET.get(path);
      if (!obj) return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
      const expiresAt = obj.customMetadata && obj.customMetadata['expires-at'];
      if (expiresAt && Date.now() > Date.parse(expiresAt)) {
        await env.BUCKET.delete(path);
        return new Response('gone — this link has expired', { status: 410, headers: { 'content-type': 'text/plain' } });
      }
      const headers = new Headers();
      obj.writeHttpMetadata(headers);
      headers.set('etag', obj.httpEtag);
      if (!headers.has('content-type')) headers.set('content-type', 'text/html; charset=utf-8');
      headers.set('cache-control', 'public, max-age=60');
      if (obj.customMetadata && obj.customMetadata.visibility === 'unlisted') {
        headers.set('X-Robots-Tag', 'noindex');
      }
      return new Response(request.method === 'HEAD' ? null : obj.body, { status: 200, headers });
    }

    if (request.method === 'DELETE') {
      const auth = await authorizeWrite(request, env);
      if (auth.error) return auth.error;
      if (auth.kind === 'phoenix') {
        const handle = phoenixHandle(auth);
        const uid = sanitizeNamespace(auth.owner);
        const delSegments = path.split('/').filter(Boolean);
        // Handle is the public namespace; userId prefix is still deletable so
        // P1 UUID-namespaced objects the same account published can be taken down.
        if (!delSegments[0] || (delSegments[0] !== handle && delSegments[0] !== uid)) {
          return json({ error: 'namespace mismatch', owner: handle || uid }, 403);
        }
      }
      await env.BUCKET.delete(path);
      return json({ ok: true, deleted: path }, 200);
    }

    return new Response('method not allowed', { status: 405 });
  },
};

// A canonical share object's key is exactly 2 segments (<user>/<slug>, or the
// sibling <user>/<slug>.png OG cover). A retained revision lives a 3rd segment
// deeper (<user>/<slug>/rev-<ts>-<rand>) — history, not a page in its own
// right, so every gallery/listing view hides it. A raw external PUT to an
// already-3-segment-deep path is treated the same way for the same reason:
// there is no ambiguity to resolve, and the CLI never produces such a key.
function isRevisionKey(key) {
  return key.split('/').length > 2;
}

async function renderGallery(bucket, origin, user, method) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: user + '/', limit: 1000, cursor, include: ['customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  const activeObjects = objects.filter(o => {
    if (isRevisionKey(o.key)) return false;
    if (o.key.endsWith('.png')) return false;
    // Unlisted pages are reachable by direct URL only — never on the gallery.
    if (o.customMetadata && o.customMetadata.visibility === 'unlisted') return false;
    const expiresAt = o.customMetadata && o.customMetadata['expires-at'];
    return !(expiresAt && Date.now() > Date.parse(expiresAt));
  });
  const items = activeObjects.map(o => {
    const slug = o.key.slice(o.key.indexOf('/') + 1);
    const url = origin + '/' + o.key;
    const label = (o.customMetadata && o.customMetadata['label']) || '';
    const agent = (o.customMetadata && o.customMetadata['agent']) || '';
    return { slug, url, updated: o.uploaded, label, agent };
  });

  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8' } });
  }

  const html =
    '<!doctype html><html><head>' +
    '<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<title>' + escapeHtml(user) + ' — agents share</title>' +
    '<style>' +
    'body{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:720px;margin:48px auto;padding:0 24px;color:#111;background:#fafafa}' +
    'h1{font-size:28px;margin-bottom:8px}a{color:#0a0a0a;text-decoration:none;border-bottom:1px solid #999}' +
    'a:hover{border-color:#111}ul{list-style:none;padding:0}li{margin:16px 0}' +
    '.slug{font-weight:600}.title{font-weight:600}.meta{color:#666;font-size:14px}' +
    '</style></head><body>' +
    '<h1>@' + escapeHtml(user) + '</h1>' +
    '<p class="meta">' + items.length + ' shared ' + (items.length === 1 ? 'page' : 'pages') + '</p>' +
    '<ul>' +
    items.map(i =>
      '<li>' +
      (i.label ? '<span class="title">' + escapeHtml(i.label) + '</span><br>' : '') +
      '<a class="slug" href="' + escapeHtml(i.url) + '">' + escapeHtml(i.slug) + '</a>' +
      '<br><span class="meta">' + new Date(i.updated).toISOString().slice(0, 10) +
      (i.agent ? ' · ' + escapeHtml(i.agent) : '') + '</span></li>'
    ).join('') +
    '</ul></body></html>';
  return new Response(html, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=60' } });
}

async function renderListing(bucket, origin, user, method) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: user + '/', limit: 1000, cursor, include: ['httpMetadata', 'customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  // Revisions never appear as their own listing row, but they count toward
  // their canonical object's revisionCount.
  const revisionCounts = {};
  for (const o of objects) {
    if (!isRevisionKey(o.key)) continue;
    const canonicalKey = o.key.split('/').slice(0, 2).join('/');
    revisionCounts[canonicalKey] = (revisionCounts[canonicalKey] || 0) + 1;
  }

  const now = Date.now();
  const items = objects
    .filter(o => {
      // Mirror the gallery: hide revisions, sibling .png OG covers, expired
      // pages, and unlisted pages — the listing is the machine-readable public surface.
      if (isRevisionKey(o.key)) return false;
      if (o.key.endsWith('.png')) return false;
      if (o.customMetadata && o.customMetadata.visibility === 'unlisted') return false;
      const expiresAt = o.customMetadata && o.customMetadata['expires-at'];
      return !(expiresAt && now > Date.parse(expiresAt));
    })
    .map(o => ({
      slug: o.key.slice(o.key.indexOf('/') + 1),
      url: origin + '/' + o.key,
      size: typeof o.size === 'number' ? o.size : 0,
      contentType: (o.httpMetadata && o.httpMetadata.contentType) || null,
      publishedAt: new Date(o.uploaded).toISOString(),
      expiresAt: (o.customMetadata && o.customMetadata['expires-at']) || null,
      label: (o.customMetadata && o.customMetadata['label']) || null,
      agent: (o.customMetadata && o.customMetadata['agent']) || null,
      session: (o.customMetadata && o.customMetadata['session']) || null,
      host: (o.customMetadata && o.customMetadata['host']) || null,
      repo: (o.customMetadata && o.customMetadata['repo']) || null,
      revisionCount: revisionCounts[o.key] || 0,
      meta: extraMetaOf(o.customMetadata),
    }));
  // Newest first, so the human table and any script reads the freshest share top.
  items.sort((a, b) => (a.publishedAt < b.publishedAt ? 1 : a.publishedAt > b.publishedAt ? -1 : 0));

  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } });
  }
  return new Response(JSON.stringify({ user, count: items.length, objects: items }), {
    status: 200,
    headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=30' },
  });
}

async function renderRevisions(bucket, origin, key, method) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: key + '/rev-', limit: 1000, cursor, include: ['httpMetadata', 'customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  const items = objects.map(o => ({
    key: o.key,
    url: origin + '/' + o.key,
    size: typeof o.size === 'number' ? o.size : 0,
    contentType: (o.httpMetadata && o.httpMetadata.contentType) || null,
    uploadedAt: new Date(o.uploaded).toISOString(),
    expiresAt: (o.customMetadata && o.customMetadata['expires-at']) || null,
    label: (o.customMetadata && o.customMetadata['label']) || null,
    agent: (o.customMetadata && o.customMetadata['agent']) || null,
    session: (o.customMetadata && o.customMetadata['session']) || null,
    host: (o.customMetadata && o.customMetadata['host']) || null,
    repo: (o.customMetadata && o.customMetadata['repo']) || null,
    meta: extraMetaOf(o.customMetadata),
  }));
  // Newest first — the most recently replaced version leads.
  items.sort((a, b) => (a.uploadedAt < b.uploadedAt ? 1 : a.uploadedAt > b.uploadedAt ? -1 : 0));

  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: { 'content-type': 'application/json; charset=utf-8' } });
  }
  return new Response(JSON.stringify({ key, count: items.length, revisions: items }), {
    status: 200,
    headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=30' },
  });
}

// The customMetadata keys the CLI sets automatically (provenance + label) —
// never a real \`--meta key=value\` entry (the CLI rejects a colliding key
// before it ever reaches this Worker; see RESERVED_META_KEYS in publish.ts).
// One list, reused both to strip a same-named --meta collision on write and
// to split arbitrary --meta entries back out on read.
var RESERVED_METADATA_KEYS = ['expires-at', 'visibility', 'owner', 'agent', 'session', 'host', 'repo', 'date', 'label', 'label-source'];

// Everything in customMetadata that ISN'T one of the reserved provenance/label
// keys above — i.e. the caller's own \`--meta key=value\` entries. Surfaced on
// every read route (listing, revisions) so a value stored with \`--meta
// kind=plan --meta ticket=RUSH-2683\` is actually visible again, not just
// write-only (RUSH-2683 review fix).
function extraMetaOf(customMetadata) {
  var out = {};
  if (!customMetadata) return out;
  for (var k in customMetadata) {
    if (RESERVED_METADATA_KEYS.indexOf(k) === -1) out[k] = customMetadata[k];
  }
  return out;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function json(body, status) {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

// Length-independent constant-time-ish compare (Workers has no timingSafeEqual).
function safeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  const la = a.length, lb = b.length;
  let out = la ^ lb;
  for (let i = 0; i < la; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i % lb || 0);
  return out === 0 && la === lb;
}

// URL-safety, not collision-resistance. Two values that differ only in
// case/punctuation share a prefix.
function sanitizeNamespace(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

// Public handle: email local-part, plus-tag stripped. Must match CLI handleFromEmail.
function handleFromEmail(email) {
  if (!email) return '';
  const local = String(email).split('@')[0] || '';
  const beforePlus = local.split('+')[0] || local;
  return sanitizeNamespace(beforePlus);
}

function phoenixHandle(auth) {
  return handleFromEmail(auth.email) || sanitizeNamespace(auth.owner);
}

// First writer of a handle owns it. Later PUTs from the same userId are fine;
// a different userId whose email local-part collides gets 409, not a silent overwrite.
async function claimHandle(bucket, handle, userId) {
  const key = '__handles/' + handle;
  const existing = await bucket.get(key);
  if (existing) {
    const claimed = existing.customMetadata && existing.customMetadata.userId;
    if (claimed && claimed !== userId) {
      return { error: json({ error: 'handle taken', handle: handle }, 409) };
    }
    return {};
  }
  await bucket.put(key, JSON.stringify({ userId: userId }), {
    httpMetadata: { contentType: 'application/json' },
    customMetadata: { userId: userId, visibility: 'unlisted' },
  });
  return {};
}

// P1 visibility: public | unlisted. 'org' (and anything else) is 400 — org is Phase 2.
function normalizeVisibility(raw) {
  const v = (raw || '').trim().toLowerCase();
  if (!v || v === 'public') return { value: 'public' };
  if (v === 'unlisted') return { value: 'unlisted' };
  if (v === 'org') return { error: json({ error: 'visibility org is not supported yet' }, 400) };
  return { error: json({ error: 'visibility must be public or unlisted' }, 400) };
}

async function defaultVerifyPhoenixToken(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return null;
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base) return null;
  let res;
  try {
    res = await fetch(base + '/api/v1/auth/me', {
      method: 'GET',
      headers: { Authorization: 'Bearer ' + presented },
    });
  } catch {
    return null;
  }
  if (!res.ok) return null;
  let body;
  try {
    body = await res.json();
  } catch {
    return null;
  }
  if (!body || typeof body.userId !== 'string' || !body.userId) return null;
  return { userId: body.userId, email: typeof body.email === 'string' ? body.email : '' };
}

// Two legitimate principals: WRITE_TOKEN equality first (admin/BYO), otherwise
// the bearer is a Phoenix token and we verify it. 401 when neither authenticates.
async function authorizeWrite(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return { error: json({ error: 'unauthorized' }, 401) };
  if (env.WRITE_TOKEN && safeEqual(presented, env.WRITE_TOKEN)) {
    return { kind: 'byo', owner: env.SHARE_NAMESPACE || 'byo' };
  }
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (claims && typeof claims.userId === 'string' && claims.userId) {
    return { kind: 'phoenix', owner: claims.userId, email: typeof claims.email === 'string' ? claims.email : '' };
  }
  return { error: json({ error: 'unauthorized' }, 401) };
}
`;
}
