// The Cloudflare Worker that fronts the R2 share bucket.
//
// One tiny Worker does both sides:
//   - PUT  /<slug>  — bearer-gated (WRITE_TOKEN secret); writes the body to R2 via
//                     the BUCKET binding, storing an optional expiry in object metadata.
//   - GET  /<slug>  — public; streams the object from R2, 410s (and lazily deletes)
//                     once its expiry has passed. A bucket lifecycle rule is the
//                     durable sweeper; this is the immediate gate.
//
// Emitted as a string (mirrors src/lib/serve/page.ts `renderPage()`), so it compiles
// into `dist/**` and ships with no package.json#files change. `provision.ts` uploads
// this verbatim as an ES-module Worker with a BUCKET (R2) binding + a WRITE_TOKEN secret.

/** Render the Worker source. Pure — the R2 binding + token are wired at deploy time. */
export function renderWorkerScript(): string {
  return `// GENERATED by agents-cli \`agents share setup\` — do not edit here; edit
// src/lib/share/worker-template.ts and re-run setup.
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const key = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));

    if (!key) {
      return new Response('agents share — POST is not it; PUT /<slug> to publish, GET /<slug> to view.', {
        status: 200, headers: { 'content-type': 'text/plain; charset=utf-8' },
      });
    }

    if (request.method === 'PUT') {
      const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
      if (!env.WRITE_TOKEN || !safeEqual(presented, env.WRITE_TOKEN)) {
        return json({ error: 'unauthorized' }, 401);
      }
      const expiresAt = request.headers.get('x-share-expires-at') || '';
      const contentType = request.headers.get('content-type') || 'text/html; charset=utf-8';
      await env.BUCKET.put(key, request.body, {
        httpMetadata: { contentType },
        customMetadata: expiresAt ? { expiresAt } : {},
      });
      return json({ ok: true, url: url.origin + '/' + key, expiresAt: expiresAt || null }, 200);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      const obj = await env.BUCKET.get(key);
      if (!obj) return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
      const expiresAt = obj.customMetadata && obj.customMetadata.expiresAt;
      if (expiresAt && Date.now() > Date.parse(expiresAt)) {
        await env.BUCKET.delete(key);
        return new Response('gone — this link has expired', { status: 410, headers: { 'content-type': 'text/plain' } });
      }
      const headers = new Headers();
      obj.writeHttpMetadata(headers);
      headers.set('etag', obj.httpEtag);
      if (!headers.has('content-type')) headers.set('content-type', 'text/html; charset=utf-8');
      headers.set('cache-control', 'public, max-age=60');
      return new Response(request.method === 'HEAD' ? null : obj.body, { status: 200, headers });
    }

    if (request.method === 'DELETE') {
      const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
      if (!env.WRITE_TOKEN || !safeEqual(presented, env.WRITE_TOKEN)) return json({ error: 'unauthorized' }, 401);
      await env.BUCKET.delete(key);
      return json({ ok: true, deleted: key }, 200);
    }

    return new Response('method not allowed', { status: 405 });
  },
};

function json(body, status) {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

// Length-independent constant-time-ish compare (Workers has no timingSafeEqual).
function safeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  const la = a.length, lb = b.length;
  let out = la ^ lb;
  for (let i = 0; i < la; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i % lb || 0);
  return out === 0 && la === lb;
}
`;
}
