// The Cloudflare Worker that fronts the R2 share bucket.
//
// One tiny Worker does both sides:
//   - PUT  /<username>/<slug>  — bearer-gated (WRITE_TOKEN secret); writes the body
//     to R2 via the BUCKET binding, storing an optional expires-at value in
//     object metadata.
//   - GET  /<username>/<slug>  — public; streams the object from R2, 410s (and lazily
//     deletes) once its expiry has passed. A bucket lifecycle rule is the durable
//     sweeper; this is the immediate gate.
//   - GET  /<username>         — public gallery of that user's shares.
//   - GET  /<slug>             — backward-compat flat slug (legacy shares before
//     per-user namespaces).
//
// Emitted as a string (mirrors src/lib/serve/page.ts `renderPage()`), so it compiles
// into `dist/**` and ships with no package.json#files change. `provision.ts` uploads
// this verbatim as an ES-module Worker with a BUCKET (R2) binding + a WRITE_TOKEN secret.

/** Render the Worker source. Pure — the R2 binding + token are wired at deploy time. */
export function renderWorkerScript(): string {
  return `// GENERATED by agents-cli agents share setup — do not edit here; edit
// src/lib/share/worker-template.ts and re-run setup.
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));

    if (!path) {
      return new Response('agents share — POST is not it; PUT /<username>/<slug> to publish, GET /<username>/<slug> to view.', {
        status: 200, headers: { 'content-type': 'text/plain; charset=utf-8' },
      });
    }

    if (request.method === 'PUT') {
      const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
      if (!env.WRITE_TOKEN || !safeEqual(presented, env.WRITE_TOKEN)) {
        return json({ error: 'unauthorized' }, 401);
      }
      const expiresAt = request.headers.get('x-share-expires-at') || '';
      const contentType = request.headers.get('content-type') || 'text/html; charset=utf-8';
      await env.BUCKET.put(path, request.body, {
        httpMetadata: { contentType },
        customMetadata: expiresAt ? { 'expires-at': expiresAt } : {},
      });
      return json({ ok: true, url: url.origin + '/' + path, expiresAt: expiresAt || null }, 200);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      // Single-segment path may be a user gallery OR a legacy flat slug.
      const segments = path.split('/').filter(Boolean);
      if (segments.length === 1) {
        const list = await env.BUCKET.list({ prefix: segments[0] + '/', limit: 1 });
        if (list.objects && list.objects.length > 0) {
          return renderGallery(env.BUCKET, url.origin, segments[0], request.method);
        }
      }

      const obj = await env.BUCKET.get(path);
      if (!obj) return new Response('not found', { status: 404, headers: { 'content-type': 'text/plain' } });
      const expiresAt = obj.customMetadata && obj.customMetadata['expires-at'];
      if (expiresAt && Date.now() > Date.parse(expiresAt)) {
        await env.BUCKET.delete(path);
        return new Response('gone — this link has expired', { status: 410, headers: { 'content-type': 'text/plain' } });
      }
      const headers = new Headers();
      obj.writeHttpMetadata(headers);
      headers.set('etag', obj.httpEtag);
      if (!headers.has('content-type')) headers.set('content-type', 'text/html; charset=utf-8');
      headers.set('cache-control', 'public, max-age=60');
      return new Response(request.method === 'HEAD' ? null : obj.body, { status: 200, headers });
    }

    if (request.method === 'DELETE') {
      const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
      if (!env.WRITE_TOKEN || !safeEqual(presented, env.WRITE_TOKEN)) return json({ error: 'unauthorized' }, 401);
      await env.BUCKET.delete(path);
      return json({ ok: true, deleted: path }, 200);
    }

    return new Response('method not allowed', { status: 405 });
  },
};

async function renderGallery(bucket, origin, user, method) {
  const objects = [];
  let cursor;
  do {
    const list = await bucket.list({ prefix: user + '/', limit: 1000, cursor, include: ['customMetadata'] });
    objects.push(...(list.objects || []));
    cursor = list.truncated ? list.cursor : undefined;
  } while (cursor);

  const activeObjects = objects.filter(o => {
    if (o.key.endsWith('.png')) return false;
    const expiresAt = o.customMetadata && o.customMetadata['expires-at'];
    return !(expiresAt && Date.now() > Date.parse(expiresAt));
  });
  const items = activeObjects.map(o => {
    const slug = o.key.slice(o.key.indexOf('/') + 1);
    const url = origin + '/' + o.key;
    return { slug, url, updated: o.uploaded };
  });

  if (method === 'HEAD') {
    return new Response(null, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8' } });
  }

  const html =
    '<!doctype html><html><head>' +
    '<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<title>' + escapeHtml(user) + ' — agents share</title>' +
    '<style>' +
    'body{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:720px;margin:48px auto;padding:0 24px;color:#111;background:#fafafa}' +
    'h1{font-size:28px;margin-bottom:8px}a{color:#0a0a0a;text-decoration:none;border-bottom:1px solid #999}' +
    'a:hover{border-color:#111}ul{list-style:none;padding:0}li{margin:16px 0}' +
    '.slug{font-weight:600}.meta{color:#666;font-size:14px}' +
    '</style></head><body>' +
    '<h1>@' + escapeHtml(user) + '</h1>' +
    '<p class="meta">' + items.length + ' shared ' + (items.length === 1 ? 'page' : 'pages') + '</p>' +
    '<ul>' +
    items.map(i =>
      '<li><a class="slug" href="' + escapeHtml(i.url) + '">' + escapeHtml(i.slug) + '</a>' +
      '<br><span class="meta">' + new Date(i.updated).toISOString().slice(0, 10) + '</span></li>'
    ).join('') +
    '</ul></body></html>';
  return new Response(html, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=60' } });
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function json(body, status) {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

// Length-independent constant-time-ish compare (Workers has no timingSafeEqual).
function safeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  const la = a.length, lb = b.length;
  let out = la ^ lb;
  for (let i = 0; i < la; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i % lb || 0);
  return out === 0 && la === lb;
}
`;
}
