// Generate the full command index for the `agents` CLI — every command and
// subcommand with its argument names and one-line description, in two forms:
//
//   docs/command-index.md    a grouped, human-scannable index (arg tokens + summary)
//   docs/command-index.json  the same tree, structured, with full option lists
//
// Both are GENERATED artifacts — never hand-edit them. Run `npm run gen:index`
// (or `bun scripts/gen-command-index.ts`); release.sh regenerates them so the
// committed index always matches the shipped command surface. `verify-docs.sh`
// fails if the committed files are stale.
//
// The source of truth is the CLI's own lazy loader table: `buildFullCommandTree`
// registers every module in `COMMAND_LOADERS` onto a throwaway program and hands
// back the real Commander tree, so this cannot drift from what the CLI registers.
// The introspection is deterministic — no LLM, no help-text parsing.
//
// Excluded by design: the inline deprecated aliases and tombstones
// (`perms`/`exec`/`jobs`/`cron`/`check`/`resources`/`hq`/`upgrade`/`_internal`),
// which src/index.ts registers directly as closures over entry-point state.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Command } from 'commander';
import { buildFullCommandTree } from '../src/lib/startup/command-registry.js';

export interface CommandArg {
  name: string;
  required: boolean;
  variadic: boolean;
}

export interface CommandOption {
  flags: string;
  description: string;
}

export interface CommandNode {
  name: string;
  path: string; // full invocation path after `agents `, e.g. "teams create"
  aliases: string[];
  description: string;
  args: CommandArg[];
  options: CommandOption[];
  subcommands: CommandNode[];
}

/** Reconstruct the usage token for an argument: `<a>`, `[a]`, `<a...>`, `[a...]`. */
export function argToken(a: CommandArg): string {
  const inner = a.variadic ? `${a.name}...` : a.name;
  return a.required ? `<${inner}>` : `[${inner}]`;
}

/** The `path arg1 arg2` invocation string (without the leading `agents `). */
export function invocation(node: CommandNode): string {
  return [node.path, ...node.args.map(argToken)].join(' ');
}

/**
 * Commander marks hidden subcommands/options with an internal `_hidden` flag and
 * exposes no public getter. The field has been stable across the commander 12.x
 * and 15.x line the CLI has used; `gen-command-index.test.ts` pins the shape.
 */
function isHidden(cmd: Command): boolean {
  return (cmd as unknown as { _hidden?: boolean })._hidden === true;
}

/** Convert one Commander command (and its whole subtree) into a plain CommandNode. */
export function toNode(cmd: Command, parentPath: string): CommandNode {
  const name = cmd.name();
  const path = parentPath ? `${parentPath} ${name}` : name;
  const args: CommandArg[] = cmd.registeredArguments.map((a) => ({
    name: a.name(),
    required: a.required,
    variadic: a.variadic,
  }));
  const options: CommandOption[] = cmd.options
    .filter((o) => !o.hidden)
    .map((o) => ({ flags: o.flags, description: (o.description ?? '').trim() }));
  const subcommands = cmd.commands
    .filter((c) => !isHidden(c))
    .sort((a, b) => a.name().localeCompare(b.name()))
    .map((c) => toNode(c, path));
  // Commander's summary() is the short one-liner when set; fall back to description().
  const summary = typeof cmd.summary === 'function' ? cmd.summary() : '';
  return {
    name,
    path,
    aliases: cmd.aliases(),
    description: (summary || cmd.description() || '').trim(),
    args,
    options,
    subcommands,
  };
}

/** Build the sorted top-level node list from a fully-registered program. */
export function walk(program: Command): CommandNode[] {
  return program.commands
    .filter((c) => !isHidden(c))
    .sort((a, b) => a.name().localeCompare(b.name()))
    .map((c) => toNode(c, ''));
}

/** Depth-first flatten of a node subtree into scannable index rows. */
function* rows(node: CommandNode): Generator<{ invocation: string; description: string }> {
  yield { invocation: invocation(node), description: node.description };
  for (const sub of node.subcommands) yield* rows(sub);
}

/** Total command count (group roots + every subcommand) across the tree. */
export function countCommands(nodes: CommandNode[]): number {
  return nodes.reduce((n, node) => n + [...rows(node)].length, 0);
}

const MD_HEADER = `<!-- GENERATED by scripts/gen-command-index.ts — DO NOT EDIT. Run \`npm run gen:index\`. -->

# Command index

Every \`agents\` command and subcommand, with its argument names and one-line
description. Generated from the CLI's own command tree, so it never drifts from
what \`agents\` actually registers.

- Regenerate: \`npm run gen:index\` (from \`apps/cli\`), or it is rebuilt on release.
- Full option lists live in the machine-readable [\`command-index.json\`](command-index.json).
- \`agents <group> --help\` shows the workflow-first help (examples + notes) for a group.

Excluded: the deprecated aliases and internal tombstones
(\`perms\`, \`exec\`, \`jobs\`, \`cron\`, \`check\`, \`resources\`, \`hq\`, \`upgrade\`, \`_internal\`).
`;

/** Render the grouped, human-scannable Markdown index. */
export function renderMarkdown(nodes: CommandNode[]): string {
  const lines: string[] = [MD_HEADER, `_${nodes.length} command groups · ${countCommands(nodes)} commands._\n`];
  for (const group of nodes) {
    const heading = group.description ? `## ${group.name} — ${group.description}` : `## ${group.name}`;
    lines.push(heading);
    if (group.aliases.length > 0) lines.push(`_aliases: ${group.aliases.join(', ')}_`);
    lines.push('');
    lines.push('```');
    const groupRows = [...rows(group)];
    const width = Math.min(Math.max(...groupRows.map((r) => r.invocation.length)) + 2, 52);
    for (const r of groupRows) {
      const inv = `agents ${r.invocation}`;
      const pad = ' '.repeat(Math.max(1, width - r.invocation.length));
      lines.push(r.description ? `${inv}${pad}${r.description}` : inv);
    }
    lines.push('```');
    lines.push('');
  }
  return lines.join('\n');
}

/** Render the structured JSON tree (full option lists included). */
export function renderJson(nodes: CommandNode[]): string {
  return JSON.stringify({ command: 'agents', groups: nodes.length, commands: countCommands(nodes), tree: nodes }, null, 2) + '\n';
}

// CLI entry — only when executed directly (bun sets import.meta.main; under
// vitest/node it is falsy, so importing the pure helpers has no side effect).
// GEN_COMMAND_INDEX_OUT_DIR overrides the output dir (verify-docs.sh regenerates
// into a temp dir to diff against the committed files); defaults to ./docs.
if ((import.meta as { main?: boolean }).main) {
  const program = await buildFullCommandTree();
  const nodes = walk(program);
  const outDir = process.env.GEN_COMMAND_INDEX_OUT_DIR ?? join(dirname(fileURLToPath(import.meta.url)), '..', 'docs');
  writeFileSync(join(outDir, 'command-index.md'), renderMarkdown(nodes));
  writeFileSync(join(outDir, 'command-index.json'), renderJson(nodes));
  console.log(`gen-command-index: wrote command-index.{md,json} to ${outDir} (${nodes.length} groups, ${countCommands(nodes)} commands)`);
}
