// The Cloudflare Worker that fronts the R2 managed session-backup bucket.
//
// SECURITY: like agents-traces (and UNLIKE agents-share), there is NO public GET
// path here. Every route — PUT, GET, LIST, DELETE — requires a Phoenix bearer
// (or a BYO static WRITE_TOKEN). The caller must be the record's owner: the
// path's first segment MUST equal the verified userId. A missing bearer → 401;
// a wrong owner → 403; public cache headers are NEVER emitted.
//
// Object payloads stay opaque to the Worker: the CLI stores each session under
//   <userId>/sessions/<machine>/<agent>/<sessionId>.jsonl          (file-shaped)
//   <userId>/sessions/<machine>/<agent>/<sessionId>/<relKey>       (dir-shaped)
// The Worker validates only that a managed PUT is a bundle whose records carry
// AES-256-GCM envelope SHAPES; it cannot decrypt, inspect, merge, or re-project
// their contents. It also enforces segments[0] === userId.
// Deliberately DIFFERENT from traces: there is NO `/all` cross-device merge here.
// Session transcripts are opaque, client-side-encrypted envelopes — merging or
// re-projecting them server-side would corrupt them — so the Worker is a pure
// per-owner blob store with a server-side LIST for restore.
//
// Reserved prefixes `__usage` (the CAS quota ledger) and `__key` (the escrowed
// backup DEK) are owner-bearer only and are NEVER returned by LIST.
//
// Routes (all require a Phoenix bearer + segments[0] === userId):
//   PUT    /<userId>/<key...>     — store an object; quota-charged (413 over quota)
//   GET    /<userId>/<key...>     — return the stored object (404 if absent)
//   GET    /<userId>/?list        — JSON array of this owner's keys (no __ prefixes),
//                                    each relative to <userId>/ (the CLI re-prepends)
//   DELETE /<userId>/<key...>     — delete an object; refunds its bytes to the ledger
//   GET    /                      — 401 (there is no public route)
//
// Emitted as a string so it compiles into dist/** with no package.json#files
// change. `provision.ts` uploads this verbatim as an ES-module Worker with a
// BUCKET (R2) binding + a PHOENIX_ID_BASE secret (+ optional self-hosted
// WRITE_TOKEN, restricted to SESSIONS_NAMESPACE or the default `byo`).

/**
 * Render the managed sessions Worker source. Pure — bindings are wired at
 * deploy time. No `${}` interpolation in the emitted source (string
 * concatenation only) so the outer template literal never captures it.
 */
export function renderSessionsWorkerScript(): string {
  return `// GENERATED by agents-cli agents sessions — do not edit; edit
// src/lib/session/sync/worker-template.ts and re-provision.
export const hooks = {
  verifyPhoenixToken: defaultVerifyPhoenixToken,
};

// Free-tier limits for one owner's backup namespace. Product behavior lives in
// code; secrets are bindings, quotas are not ambient deployment knobs.
const PLAN = { maxBytes: 5 * 1024 * 1024 * 1024, maxObjects: 200000, maxFileBytes: 64 * 1024 * 1024 };

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    let path;
    try {
      path = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));
    } catch {
      return json({ error: 'malformed object path' }, 400);
    }

    if (!path) {
      return json({ error: 'unauthorized' }, 401);
    }

    if (request.method === 'PUT') {
      return handlePut(request, env, path);
    }
    if (request.method === 'GET' || request.method === 'HEAD') {
      return handleGet(request, env, path, url);
    }
    if (request.method === 'DELETE') {
      return handleDelete(request, env, path);
    }
    return json({ error: 'method not allowed' }, 405);
  },
};

// The reserved first-key-segment prefixes: owner-bearer only, never listed, and
// never quota-charged/refunded (the ledger and the DEK are infrastructure, not
// user payload).
function isReservedRelKey(rel) {
  const first = rel.split('/').filter(Boolean)[0] || '';
  return first === '__usage' || first === '__key';
}

async function handlePut(request, env, path) {
  const auth = await authorizeWrite(request, env);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const owner = auth.owner;
  if (!owner || segments[0] !== owner) {
    return json({ error: 'namespace mismatch', owner: owner }, 403);
  }
  const rel = segments.slice(1).join('/');
  if (!rel) return json({ error: 'missing object key' }, 400);

  const reserved = isReservedRelKey(rel);
  const isEscrow = rel === '__key/backup-dek';
  if (reserved && !isEscrow) {
    return json({ error: 'reserved object key' }, 403);
  }
  const contentType = request.headers.get('content-type') || 'application/octet-stream';

  // Read the body bounded to the per-file cap so a streaming body can never OOM
  // the Worker or slip past the quota by lying about its length.
  const read = await readBodyBounded(request, PLAN.maxFileBytes);
  if (read.oversize) {
    return json({ error: 'file too large', maxBytes: PLAN.maxFileBytes }, 413);
  }
  const body = read.bytes;

  // The escrow key is immutable: all first-use devices conditionally create it,
  // then losers read the one winner before encrypting a transcript.
  if (isEscrow) {
    const created = await env.BUCKET.put(path, body, {
      httpMetadata: { contentType: contentType },
      customMetadata: { owner: owner, uploadedAt: new Date().toISOString() },
      onlyIf: { etagDoesNotMatch: '*' },
    });
    if (created === null) return json({ error: 'already exists', key: path }, 409);
    return json({ ok: true, key: path }, 200);
  }

  if (!reserved && auth.kind === 'phoenix') {
    // Managed storage accepts ciphertext bundles only. This is intentionally a
    // shape check, not decryption: it closes direct-client/plaintext bypasses
    // while transcripts remain opaque to Phoenix and the Worker.
    if (!rel.startsWith('sessions/') || !isEncryptedSessionBundle(body)) {
      return json({ error: 'managed session body must be an AES-256-GCM bundle' }, 400);
    }

    // Charge the byte DELTA against the owner's ledger. A PUT overwriting an
    // existing object only charges the difference; a fresh key charges its full
    // size and increments the object count.
    const prior = await env.BUCKET.head(path);
    const priorBytes = prior && typeof prior.size === 'number' ? prior.size : 0;
    const delta = body.byteLength - priorBytes;
    const charge = await chargeSessionWrite(env, owner, {
      fileBytes: body.byteLength,
      priorBytes: priorBytes,
      isNew: !prior,
    }, PLAN);
    if (charge.error) return charge.error;

    const putOpts = {
      httpMetadata: { contentType: contentType },
      customMetadata: { owner: owner, uploadedAt: new Date().toISOString() },
      onlyIf: prior && prior.etag ? { etagMatches: prior.etag } : { etagDoesNotMatch: '*' },
    };
    try {
      const stored = await env.BUCKET.put(path, body, putOpts);
      if (stored === null) {
        const refunded = await refundSessionWrite(env, owner, { bytes: delta, count: prior ? 0 : 1 });
        if (!refunded) return json({ error: 'usage refund contended; retry or reconcile' }, 503);
        return json({ error: 'conflict', key: path }, 409);
      }
    } catch (err) {
      const refunded = await refundSessionWrite(env, owner, { bytes: delta, count: prior ? 0 : 1 });
      if (!refunded) return json({ error: 'usage refund contended; retry or reconcile' }, 503);
      throw err;
    }
  } else {
    // Static WRITE_TOKEN is the self-hosted/operator principal and uses its own
    // bucket, so it mirrors share by bypassing managed per-user quota.
    await env.BUCKET.put(path, body, {
      httpMetadata: { contentType: contentType },
      customMetadata: { owner: owner, uploadedAt: new Date().toISOString() },
    });
  }

  const headers = new Headers();
  headers.set('content-type', 'application/json; charset=utf-8');
  headers.set('cache-control', 'private, no-store');
  return new Response(JSON.stringify({ ok: true, key: path }), { status: 200, headers });
}

async function handleGet(request, env, path, url) {
  const auth = await authorizeRead(request, env, path);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const owner = segments[0];

  // GET /<userId>/?list — enumerate this owner's keys (never the __ reserved
  // prefixes), each relative to <userId>/ so the CLI re-prepends inside its
  // client (BYO object layout stays identical).
  if (segments.length === 1 && url.searchParams.has('list')) {
    const keys = await listOwnerKeys(env, owner);
    const headers = new Headers();
    headers.set('content-type', 'application/json; charset=utf-8');
    headers.set('cache-control', 'private, no-store');
    return new Response(JSON.stringify({ keys: keys }), { status: 200, headers });
  }

  const object = await env.BUCKET.get(path);
  if (!object) return json({ error: 'not found' }, 404);

  const headers = new Headers(object.httpMetadata ?? {});
  headers.set('cache-control', 'private, no-store');
  return new Response(request.method === 'HEAD' ? null : object.body, { headers });
}

async function handleDelete(request, env, path) {
  const auth = await authorizeWrite(request, env);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const owner = auth.owner;
  if (!owner || segments[0] !== owner) {
    return json({ error: 'namespace mismatch', owner: owner }, 403);
  }
  const rel = segments.slice(1).join('/');
  if (!rel) return json({ error: 'missing object key' }, 400);

  const reserved = isReservedRelKey(rel);
  if (reserved) {
    // Reserved infrastructure records are not user-deletable: deleting the
    // immutable escrow would orphan ciphertext on the next fresh-device mint.
    return json({ error: 'reserved object key' }, 403);
  }
  const existing = await env.BUCKET.head(path);
  if (existing && auth.kind === 'phoenix') {
    const size = typeof existing.size === 'number' ? existing.size : 0;
    // Refund BEFORE deletion. If the CAS remains contended after bounded
    // retries, fail loud and leave the object intact so the caller can retry;
    // never report a successful delete while permanently overcharging quota.
    const refunded = await refundSessionWrite(env, owner, { bytes: size, count: 1 });
    if (!refunded) return json({ error: 'usage refund contended; retry or reconcile' }, 503);
  }
  await env.BUCKET.delete(path);

  const headers = new Headers();
  headers.set('content-type', 'application/json; charset=utf-8');
  headers.set('cache-control', 'private, no-store');
  return new Response(JSON.stringify({ ok: true, key: path }), { status: 200, headers });
}

// Enumerate every stored key under <owner>/, EXCLUDING the reserved __ prefixes,
// returning each stripped of the <owner>/ prefix. Paginates R2's cursor so a
// large backup set lists completely.
async function listOwnerKeys(env, owner) {
  const base = owner + '/';
  const out = [];
  let cursor = undefined;
  do {
    const listed = await env.BUCKET.list(cursor ? { prefix: base, cursor: cursor } : { prefix: base });
    const objects = (listed && listed.objects) || [];
    for (const o of objects) {
      const key = o.key || '';
      if (!key.startsWith(base)) continue;
      const rel = key.slice(base.length);
      if (!rel || isReservedRelKey(rel)) continue;
      out.push(rel);
    }
    cursor = listed && listed.truncated ? listed.cursor : undefined;
  } while (cursor);
  return out.sort();
}

// --- Per-user usage ledger (R2 conditional-put CAS), mirrored from agents-share.
// A single object at __usage/<owner> holds { bytes, count } for one user. R2 has
// no atomic increment, so mutations use read → mutate → conditional-put
// (onlyIf.etagMatches). The __usage key is reserved: owner-bearer only, never
// listed.
function usageKey(owner) { return '__usage/' + owner; }

function usageNumber(v, dflt) {
  const n = typeof v === 'number' ? v : parseFloat(v);
  return Number.isFinite(n) && n >= 0 ? n : dflt;
}

async function readUsage(env, owner) {
  const obj = await env.BUCKET.get(usageKey(owner));
  if (!obj) return { etag: null, usage: { bytes: 0, count: 0 } };
  let usage = { bytes: 0, count: 0 };
  try {
    const raw = typeof obj.text === 'function' ? await obj.text() : '';
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object') {
      usage = { bytes: usageNumber(parsed.bytes, 0), count: usageNumber(parsed.count, 0) };
    }
  } catch (e) {
    // Malformed ledger — treat as fresh zero but KEEP the etag so the next CAS
    // put overwrites the corrupt object rather than looping against it forever.
  }
  return { etag: obj.etag || null, usage: usage };
}

async function writeUsageCas(env, owner, prevEtag, usage) {
  const body = JSON.stringify(usage);
  const opts = { httpMetadata: { contentType: 'application/json' } };
  if (prevEtag) {
    opts.onlyIf = { etagMatches: prevEtag };
    const res = await env.BUCKET.put(usageKey(owner), body, opts);
    return res !== null;
  }
  opts.onlyIf = { etagDoesNotMatch: '*' };
  const res = await env.BUCKET.put(usageKey(owner), body, opts);
  return res !== null;
}

// CAS retry loop. fn(usage) returns { reject: Response } to fail loud without
// committing, or { commit: usage } to persist. On CAS contention it re-reads and
// retries; exhausting the retries fails loud with 503.
async function withUsage(env, owner, fn) {
  for (let attempt = 0; attempt < 6; attempt++) {
    const state = await readUsage(env, owner);
    const outcome = fn(state.usage);
    if (outcome.reject) return outcome.reject;
    const ok = await writeUsageCas(env, owner, state.etag, outcome.commit);
    if (ok) return null;
  }
  return json({ error: 'usage ledger contended, retry' }, 503);
}

// Charge one authed PUT against the owner's ledger: per-file cap → object count
// → byte quota, each failing loud (413) before anything is written. Returns
// { error: Response } on rejection, else {}.
async function chargeSessionWrite(env, owner, params, limits) {
  if (typeof params.fileBytes === 'number' && params.fileBytes > limits.maxFileBytes) {
    return { error: json({ error: 'file too large', maxBytes: limits.maxFileBytes, gotBytes: params.fileBytes }, 413) };
  }
  const rejection = await withUsage(env, owner, function (usage) {
    if (params.isNew) {
      if (usage.count + 1 > limits.maxObjects) {
        return { reject: json({ error: 'artifact limit reached', maxObjects: limits.maxObjects }, 413) };
      }
      usage.count += 1;
    }
    const delta = params.fileBytes - (params.priorBytes || 0);
    if (usage.bytes + delta > limits.maxBytes) {
      return { reject: json({ error: 'storage limit reached', maxBytes: limits.maxBytes, usedBytes: usage.bytes }, 413) };
    }
    usage.bytes = Math.max(0, usage.bytes + delta);
    return { commit: usage };
  });
  if (rejection instanceof Response) return { error: rejection };
  return {};
}

// Refund on DELETE/failed PUT. Never creates a ledger: if the owner was never
// charged (no __usage object) it is a successful no-op. Returns false only
// after bounded CAS contention so callers can fail loud.
async function refundSessionWrite(env, owner, params) {
  for (let attempt = 0; attempt < 6; attempt++) {
    const state = await readUsage(env, owner);
    if (!state.etag) return true; // nothing was ever charged
    state.usage.bytes = Math.max(0, state.usage.bytes - (params.bytes || 0));
    state.usage.count = Math.max(0, state.usage.count - (params.count || 0));
    if (await writeUsageCas(env, owner, state.etag, state.usage)) return true;
  }
  return false;
}

// A Phoenix-managed payload is exactly one or more bundle records and every
// body has the transcript-crypto AES-256-GCM envelope shape. The Worker never
// receives the DEK, so this deliberately validates structure without decrypting.
function isEncryptedSessionBundle(bytes) {
  let text;
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch {
    return false;
  }
  const lines = text.split(/\\r?\\n/).filter(function (line) { return line.trim().length > 0; });
  if (lines.length < 2) return false;
  let header;
  try { header = JSON.parse(lines[0]); } catch { return false; }
  if (!header || header.kind !== 'agents-session-bundle' || header.version !== 1 || header.encrypted !== true) return false;
  if (header.count !== lines.length - 1 || header.count < 1) return false;
  for (let i = 1; i < lines.length; i++) {
    let record;
    let envelope;
    try {
      record = JSON.parse(lines[i]);
      envelope = record && typeof record.body === 'string' ? JSON.parse(record.body) : null;
    } catch {
      return false;
    }
    if (!record || record.encrypted !== true || !isAesGcmEnvelope(envelope)) return false;
  }
  return true;
}

function isAesGcmEnvelope(value) {
  return !!value && value.v === 1 && value.alg === 'aes-256-gcm' &&
    base64ByteLength(value.iv) === 12 && base64ByteLength(value.tag) === 16 &&
    base64ByteLength(value.ct) >= 0;
}

function base64ByteLength(value) {
  if (typeof value !== 'string') return -1;
  try { return atob(value).length; } catch { return -1; }
}

// Read a request body fully into memory, BOUNDED: abort the moment it exceeds
// maxBytes. Returns { oversize: true, size } once the cap is passed, else
// { bytes, size } with the exact bytes.
async function readBodyBounded(request, maxBytes) {
  if (!request.body || typeof request.body.getReader !== 'function') {
    const buf = await request.arrayBuffer();
    const bytes = new Uint8Array(buf);
    if (bytes.byteLength > maxBytes) return { oversize: true, size: bytes.byteLength };
    return { bytes: bytes, size: bytes.byteLength };
  }
  const reader = request.body.getReader();
  const chunks = [];
  let size = 0;
  while (true) {
    const step = await reader.read();
    if (step.done) break;
    const chunk = step.value;
    size += chunk.byteLength;
    if (size > maxBytes) {
      try { await reader.cancel(); } catch (e) { /* best-effort */ }
      return { oversize: true, size: size };
    }
    chunks.push(chunk);
  }
  const out = new Uint8Array(size);
  let offset = 0;
  for (let i = 0; i < chunks.length; i++) { out.set(chunks[i], offset); offset += chunks[i].byteLength; }
  return { bytes: out, size: size };
}

// Require a Phoenix bearer that owns the path prefix. No public GET, ever.
async function authorizeRead(request, env, path) {
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (!claims) {
    // A BYO static WRITE_TOKEN is also a legitimate read principal for its own
    // namespace (self-hosted operator with no Phoenix).
    const byo = byoOwner(request, env);
    if (byo) {
      const ownerId = path.split('/').filter(Boolean)[0] || '';
      if (ownerId && ownerId === byo) return { owner: byo };
    }
    return { error: json({ error: 'unauthorized' }, 401) };
  }
  const ownerId = path.split('/').filter(Boolean)[0] || '';
  if (!ownerId || ownerId !== claims.userId) {
    return { error: json({ error: 'forbidden' }, 403) };
  }
  return { claims: claims, owner: claims.userId };
}

// Two legitimate write principals: a self-hosted static WRITE_TOKEN confined to
// its configured namespace, else a Phoenix bearer. The static principal cannot
// write or read a managed user's prefix. 401 when neither authenticates.
async function authorizeWrite(request, env) {
  const byo = byoOwner(request, env);
  if (byo) return { kind: 'byo', owner: byo };
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (claims && typeof claims.userId === 'string' && claims.userId) {
    return { kind: 'phoenix', owner: claims.userId };
  }
  return { error: json({ error: 'unauthorized' }, 401) };
}

function byoOwner(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (presented && env.WRITE_TOKEN && safeEqual(presented, env.WRITE_TOKEN)) {
    return env.SESSIONS_NAMESPACE || 'byo';
  }
  return null;
}

async function defaultVerifyPhoenixToken(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return null;
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base) return null;
  let res;
  try {
    res = await fetch(base + '/api/v1/auth/me', {
      method: 'GET',
      headers: { Authorization: 'Bearer ' + presented },
    });
  } catch {
    return null;
  }
  if (!res.ok) return null;
  let body;
  try {
    body = await res.json();
  } catch {
    return null;
  }
  if (!body || typeof body.userId !== 'string' || !body.userId) return null;
  return { userId: body.userId, email: typeof body.email === 'string' ? body.email : '' };
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'private, no-store',
    },
  });
}

// Constant-time comparison so timing attacks can't probe a static WRITE_TOKEN.
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
`;
}
