// The Cloudflare Worker that fronts the R2 managed session-backup bucket.
//
// SECURITY: like agents-traces (and UNLIKE agents-share), there is NO public GET
// path here. Every route — PUT, GET, LIST, DELETE — requires a Phoenix bearer;
// there is NO static-token principal (the zero-knowledge BYO path talks to the
// user's own R2 bucket directly and never reaches this Worker, so a WRITE_TOKEN
// here would only be a Phoenix-and-quota bypass — PHNX-3726). The caller must be
// the record's owner: the path's first segment MUST equal the verified userId. A
// missing bearer → 401; a wrong owner → 403; public cache headers are NEVER
// emitted. A stored transcript body MUST be an AES-256-GCM envelope — a plaintext
// PUT is rejected 422 so readable transcript content can never land in the bucket.
//
// Object layout is OPAQUE to the Worker: the CLI stores each session under
//   <userId>/sessions/<machine>/<agent>/<sessionId>.jsonl          (file-shaped)
//   <userId>/sessions/<machine>/<agent>/<sessionId>/<relKey>       (dir-shaped)
// but the Worker only enforces segments[0] === userId and never parses the rest.
// Deliberately DIFFERENT from traces: there is NO `/all` cross-device merge here.
// Session transcripts are opaque, client-side-encrypted envelopes — merging or
// re-projecting them server-side would corrupt them — so the Worker is a pure
// per-owner blob store with a server-side LIST for restore.
//
// Reserved prefixes `__usage` (the CAS quota ledger) and `__key` (the escrowed
// backup DEK) are owner-bearer only and are NEVER returned by LIST.
//
// Routes (all require a Phoenix bearer + segments[0] === userId):
//   PUT    /<userId>/<key...>     — store an object; quota-charged (413 over quota)
//   GET    /<userId>/<key...>     — return the stored object (404 if absent)
//   GET    /<userId>/?list        — JSON array of this owner's keys (no __ prefixes),
//                                    each relative to <userId>/ (the CLI re-prepends)
//   DELETE /<userId>/<key...>     — delete an object; refunds its bytes to the ledger
//   GET    /                      — 401 (there is no public route)
//
// Emitted as a string so it compiles into dist/** with no package.json#files
// change. `provision.ts` uploads this verbatim as an ES-module Worker with a
// BUCKET (R2) binding + a PHOENIX_ID_BASE secret.

/**
 * Render the managed sessions Worker source. Pure — bindings are wired at
 * deploy time. No `${}` interpolation in the emitted source (string
 * concatenation only) so the outer template literal never captures it.
 */
export function renderSessionsWorkerScript(): string {
  return `// GENERATED by agents-cli agents sessions — do not edit; edit
// src/lib/session/sync/worker-template.ts and re-provision.
export const hooks = {
  verifyPhoenixToken: defaultVerifyPhoenixToken,
};

// Free-tier limits for one owner's backup namespace. Product behavior lives in
// code; secrets are bindings, quotas are not ambient deployment knobs.
const PLAN = { maxBytes: 5 * 1024 * 1024 * 1024, maxObjects: 200000, maxFileBytes: 64 * 1024 * 1024 };

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    let path;
    try {
      path = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));
    } catch {
      return json({ error: 'malformed object path' }, 400);
    }

    if (!path) {
      return json({ error: 'unauthorized' }, 401);
    }

    if (request.method === 'PUT') {
      return handlePut(request, env, path);
    }
    if (request.method === 'GET' || request.method === 'HEAD') {
      return handleGet(request, env, path, url);
    }
    if (request.method === 'DELETE') {
      return handleDelete(request, env, path);
    }
    return json({ error: 'method not allowed' }, 405);
  },
};

// The reserved first-key-segment prefixes: owner-bearer only, never listed, and
// never quota-charged/refunded (the ledger and the DEK are infrastructure, not
// user payload).
function isReservedRelKey(rel) {
  const first = rel.split('/').filter(Boolean)[0] || '';
  return first === '__usage' || first === '__key';
}

async function handlePut(request, env, path) {
  const auth = await authorizeWrite(request, env);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const owner = auth.owner;
  if (!owner || segments[0] !== owner) {
    return json({ error: 'namespace mismatch', owner: owner }, 403);
  }
  const rel = segments.slice(1).join('/');
  if (!rel) return json({ error: 'missing object key' }, 400);

  const reserved = isReservedRelKey(rel);
  const isEscrow = rel === '__key/backup-dek';
  if (reserved && !isEscrow) {
    return json({ error: 'reserved object key' }, 403);
  }
  const contentType = request.headers.get('content-type') || 'application/octet-stream';

  // Read the body bounded to the per-file cap so a streaming body can never OOM
  // the Worker or slip past the quota by lying about its length.
  const read = await readBodyBounded(request, PLAN.maxFileBytes);
  if (read.oversize) {
    return json({ error: 'file too large', maxBytes: PLAN.maxFileBytes }, 413);
  }
  const body = read.bytes;

  // The escrow key is immutable: all first-use devices conditionally create it,
  // then losers read the one winner before encrypting a transcript.
  if (isEscrow) {
    const created = await env.BUCKET.put(path, body, {
      httpMetadata: { contentType: contentType },
      customMetadata: { owner: owner, uploadedAt: new Date().toISOString() },
      onlyIf: { etagDoesNotMatch: '*' },
    });
    if (created === null) return json({ error: 'already exists', key: path }, 409);
    return json({ ok: true, key: path }, 200);
  }

  // Fail closed on a plaintext payload: a managed transcript bundle is always
  // client-side-encrypted (SES-51), so an unencrypted bundle here is an
  // older/buggy client and MUST be rejected before it lands readable.
  if (!isEncryptedManagedBundle(body)) {
    return json({ error: 'payload must be an encrypted bundle' }, 422);
  }

  // Charge the byte DELTA against the owner's ledger. A PUT overwriting an
  // existing object only charges the difference; a fresh key charges its full
  // size and increments the object count.
  const prior = await env.BUCKET.head(path);
  const priorBytes = prior && typeof prior.size === 'number' ? prior.size : 0;
  const delta = body.byteLength - priorBytes;
  const charge = await chargeSessionWrite(env, owner, {
    fileBytes: body.byteLength,
    priorBytes: priorBytes,
    isNew: !prior,
  }, PLAN);
  if (charge.error) return charge.error;

  const putOpts = {
    httpMetadata: { contentType: contentType },
    customMetadata: { owner: owner, uploadedAt: new Date().toISOString() },
    onlyIf: prior && prior.etag ? { etagMatches: prior.etag } : { etagDoesNotMatch: '*' },
  };
  try {
    const stored = await env.BUCKET.put(path, body, putOpts);
    if (stored === null) {
      await refundSessionWrite(env, owner, { bytes: delta, count: prior ? 0 : 1 });
      return json({ error: 'conflict', key: path }, 409);
    }
  } catch (err) {
    await refundSessionWrite(env, owner, { bytes: delta, count: prior ? 0 : 1 });
    throw err;
  }

  const headers = new Headers();
  headers.set('content-type', 'application/json; charset=utf-8');
  headers.set('cache-control', 'private, no-store');
  return new Response(JSON.stringify({ ok: true, key: path }), { status: 200, headers });
}

async function handleGet(request, env, path, url) {
  const auth = await authorizeRead(request, env, path);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const owner = segments[0];

  // GET /<userId>/?list — enumerate this owner's keys (never the __ reserved
  // prefixes), each relative to <userId>/ so the CLI re-prepends inside its
  // client (BYO object layout stays identical).
  if (segments.length === 1 && url.searchParams.has('list')) {
    const keys = await listOwnerKeys(env, owner);
    const headers = new Headers();
    headers.set('content-type', 'application/json; charset=utf-8');
    headers.set('cache-control', 'private, no-store');
    return new Response(JSON.stringify({ keys: keys }), { status: 200, headers });
  }

  const object = await env.BUCKET.get(path);
  if (!object) return json({ error: 'not found' }, 404);

  const headers = new Headers(object.httpMetadata ?? {});
  headers.set('cache-control', 'private, no-store');
  return new Response(request.method === 'HEAD' ? null : object.body, { headers });
}

async function handleDelete(request, env, path) {
  const auth = await authorizeWrite(request, env);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const owner = auth.owner;
  if (!owner || segments[0] !== owner) {
    return json({ error: 'namespace mismatch', owner: owner }, 403);
  }
  const rel = segments.slice(1).join('/');
  if (!rel) return json({ error: 'missing object key' }, 400);

  const reserved = isReservedRelKey(rel);
  if (reserved) {
    // Reserved infrastructure records are not user-deletable: deleting the
    // immutable escrow would orphan ciphertext on the next fresh-device mint.
    return json({ error: 'reserved object key' }, 403);
  }
  const existing = await env.BUCKET.head(path);
  await env.BUCKET.delete(path);
  if (existing) {
    // Reconcile the ledger from the real bucket rather than refunding a fixed
    // delta. R2 has no conditional delete, so two concurrent DELETEs of one key
    // would each refund its bytes and let an owner inflate their own quota; a
    // recompute is idempotent (settles on the true remaining usage regardless of
    // how many deletes raced) and convergent (never silently drops the mutation
    // when the CAS is contended).
    await reconcileUsage(env, owner);
  }

  const headers = new Headers();
  headers.set('content-type', 'application/json; charset=utf-8');
  headers.set('cache-control', 'private, no-store');
  return new Response(JSON.stringify({ ok: true, key: path }), { status: 200, headers });
}

// Enumerate every stored key under <owner>/, EXCLUDING the reserved __ prefixes,
// returning each stripped of the <owner>/ prefix. Paginates R2's cursor so a
// large backup set lists completely.
async function listOwnerKeys(env, owner) {
  const base = owner + '/';
  const out = [];
  let cursor = undefined;
  do {
    const listed = await env.BUCKET.list(cursor ? { prefix: base, cursor: cursor } : { prefix: base });
    const objects = (listed && listed.objects) || [];
    for (const o of objects) {
      const key = o.key || '';
      if (!key.startsWith(base)) continue;
      const rel = key.slice(base.length);
      if (!rel || isReservedRelKey(rel)) continue;
      out.push(rel);
    }
    cursor = listed && listed.truncated ? listed.cursor : undefined;
  } while (cursor);
  return out.sort();
}

// --- Per-user usage ledger (R2 conditional-put CAS), mirrored from agents-share.
// A single object at __usage/<owner> holds { bytes, count } for one user. R2 has
// no atomic increment, so mutations use read → mutate → conditional-put
// (onlyIf.etagMatches). The __usage key is reserved: owner-bearer only, never
// listed.
function usageKey(owner) { return '__usage/' + owner; }

function usageNumber(v, dflt) {
  const n = typeof v === 'number' ? v : parseFloat(v);
  return Number.isFinite(n) && n >= 0 ? n : dflt;
}

async function readUsage(env, owner) {
  const obj = await env.BUCKET.get(usageKey(owner));
  if (!obj) return { etag: null, usage: { bytes: 0, count: 0 } };
  let usage = { bytes: 0, count: 0 };
  try {
    const raw = typeof obj.text === 'function' ? await obj.text() : '';
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object') {
      usage = { bytes: usageNumber(parsed.bytes, 0), count: usageNumber(parsed.count, 0) };
    }
  } catch (e) {
    // Malformed ledger — treat as fresh zero but KEEP the etag so the next CAS
    // put overwrites the corrupt object rather than looping against it forever.
  }
  return { etag: obj.etag || null, usage: usage };
}

async function writeUsageCas(env, owner, prevEtag, usage) {
  const body = JSON.stringify(usage);
  const opts = { httpMetadata: { contentType: 'application/json' } };
  if (prevEtag) {
    opts.onlyIf = { etagMatches: prevEtag };
    const res = await env.BUCKET.put(usageKey(owner), body, opts);
    return res !== null;
  }
  opts.onlyIf = { etagDoesNotMatch: '*' };
  const res = await env.BUCKET.put(usageKey(owner), body, opts);
  return res !== null;
}

// CAS retry loop. fn(usage) returns { reject: Response } to fail loud without
// committing, or { commit: usage } to persist. On CAS contention it re-reads and
// retries; exhausting the retries fails loud with 503.
async function withUsage(env, owner, fn) {
  for (let attempt = 0; attempt < 6; attempt++) {
    const state = await readUsage(env, owner);
    const outcome = fn(state.usage);
    if (outcome.reject) return outcome.reject;
    const ok = await writeUsageCas(env, owner, state.etag, outcome.commit);
    if (ok) return null;
  }
  return json({ error: 'usage ledger contended, retry' }, 503);
}

// Charge one authed PUT against the owner's ledger: per-file cap → object count
// → byte quota, each failing loud (413) before anything is written. Returns
// { error: Response } on rejection, else {}.
async function chargeSessionWrite(env, owner, params, limits) {
  if (typeof params.fileBytes === 'number' && params.fileBytes > limits.maxFileBytes) {
    return { error: json({ error: 'file too large', maxBytes: limits.maxFileBytes, gotBytes: params.fileBytes }, 413) };
  }
  const rejection = await withUsage(env, owner, function (usage) {
    if (params.isNew) {
      if (usage.count + 1 > limits.maxObjects) {
        return { reject: json({ error: 'artifact limit reached', maxObjects: limits.maxObjects }, 413) };
      }
      usage.count += 1;
    }
    const delta = params.fileBytes - (params.priorBytes || 0);
    if (usage.bytes + delta > limits.maxBytes) {
      return { reject: json({ error: 'storage limit reached', maxBytes: limits.maxBytes, usedBytes: usage.bytes }, 413) };
    }
    usage.bytes = Math.max(0, usage.bytes + delta);
    return { commit: usage };
  });
  if (rejection instanceof Response) return { error: rejection };
  return {};
}

// Refund a failed PUT's charge. Never rejects, never creates a ledger: if the
// owner was never charged (no __usage object) it is a pure no-op. When the CAS
// stays contended past the retry budget it converges to the authoritative truth
// rather than silently dropping the refund (PHNX-3726 fix-forward).
async function refundSessionWrite(env, owner, params) {
  for (let attempt = 0; attempt < 6; attempt++) {
    const state = await readUsage(env, owner);
    if (!state.etag) return; // nothing was ever charged
    state.usage.bytes = Math.max(0, state.usage.bytes - (params.bytes || 0));
    state.usage.count = Math.max(0, state.usage.count - (params.count || 0));
    if (await writeUsageCas(env, owner, state.etag, state.usage)) return;
  }
  await reconcileUsage(env, owner);
}

// Authoritatively recompute { bytes, count } from the owner's real objects
// (excluding the reserved __ prefixes) and commit it. This is the convergent
// backstop for the delta ledger: idempotent under concurrent mutations and
// self-correcting when a delta CAS is lost, so the ledger cannot drift into
// permanently over- or under-charging a user. Bounded retry; on a persistently
// contended CAS the next mutation reconciles again.
async function reconcileUsage(env, owner) {
  const base = owner + '/';
  let bytes = 0;
  let count = 0;
  let cursor = undefined;
  do {
    const listed = await env.BUCKET.list(cursor ? { prefix: base, cursor: cursor } : { prefix: base });
    const objects = (listed && listed.objects) || [];
    for (const o of objects) {
      const key = o.key || '';
      if (!key.startsWith(base)) continue;
      const rel = key.slice(base.length);
      if (!rel || isReservedRelKey(rel)) continue;
      bytes += typeof o.size === 'number' ? o.size : 0;
      count += 1;
    }
    cursor = listed && listed.truncated ? listed.cursor : undefined;
  } while (cursor);
  for (let attempt = 0; attempt < 6; attempt++) {
    const state = await readUsage(env, owner);
    if (await writeUsageCas(env, owner, state.etag, { bytes: bytes, count: count })) return true;
  }
  return false;
}

// Read a request body fully into memory, BOUNDED: abort the moment it exceeds
// maxBytes. Returns { oversize: true, size } once the cap is passed, else
// { bytes, size } with the exact bytes.
async function readBodyBounded(request, maxBytes) {
  if (!request.body || typeof request.body.getReader !== 'function') {
    const buf = await request.arrayBuffer();
    const bytes = new Uint8Array(buf);
    if (bytes.byteLength > maxBytes) return { oversize: true, size: bytes.byteLength };
    return { bytes: bytes, size: bytes.byteLength };
  }
  const reader = request.body.getReader();
  const chunks = [];
  let size = 0;
  while (true) {
    const step = await reader.read();
    if (step.done) break;
    const chunk = step.value;
    size += chunk.byteLength;
    if (size > maxBytes) {
      try { await reader.cancel(); } catch (e) { /* best-effort */ }
      return { oversize: true, size: size };
    }
    chunks.push(chunk);
  }
  const out = new Uint8Array(size);
  let offset = 0;
  for (let i = 0; i < chunks.length; i++) { out.set(chunks[i], offset); offset += chunks[i].byteLength; }
  return { bytes: out, size: size };
}

// Require a Phoenix bearer that owns the path prefix. No public GET, ever.
// This managed store is Phoenix-only: there is no static-token principal. The
// zero-knowledge BYO path talks to the operator's OWN R2 bucket directly through
// the CLI's R2Client and never reaches this Worker, so a WRITE_TOKEN here would
// be a Phoenix-and-quota bypass with no legitimate caller — it is deliberately
// absent (PHNX-3726 fix-forward).
async function authorizeRead(request, env, path) {
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (!claims) {
    return { error: json({ error: 'unauthorized' }, 401) };
  }
  const ownerId = path.split('/').filter(Boolean)[0] || '';
  if (!ownerId || ownerId !== claims.userId) {
    return { error: json({ error: 'forbidden' }, 403) };
  }
  return { claims: claims, owner: claims.userId };
}

// The single write principal is a Phoenix bearer whose verified userId owns the
// path prefix. 401 when it does not authenticate.
async function authorizeWrite(request, env) {
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (claims && typeof claims.userId === 'string' && claims.userId) {
    return { owner: claims.userId };
  }
  return { error: json({ error: 'unauthorized' }, 401) };
}

// A stored managed body MUST be an ENCRYPTED bundle — never plaintext (SES-51).
// The upload wire is NDJSON: a header line then one record line per transcript
// (serializeBundle). This Worker independently re-checks what the CLI already
// fails-closed on before upload: the header claims encryption AND every record
// body is a real AES-256-GCM transcript envelope (v/alg/iv/ct/tag), so an
// older/buggy client's plaintext PUT is rejected 422 rather than landing readable
// in the bucket. Reserved __key / __usage records are exempt (not user payload).
function isTranscriptEnvelopeString(body) {
  if (typeof body !== 'string') return false;
  const trimmed = body.trimStart();
  if (!trimmed.startsWith('{')) return false;
  let obj;
  try {
    obj = JSON.parse(body);
  } catch {
    return false;
  }
  return !!obj
    && typeof obj === 'object'
    && obj.v === 1
    && typeof obj.alg === 'string' && obj.alg.length > 0
    && typeof obj.iv === 'string' && obj.iv.length > 0
    && typeof obj.ct === 'string'
    && typeof obj.tag === 'string' && obj.tag.length > 0;
}

function isEncryptedManagedBundle(bytes) {
  let text;
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch {
    return false;
  }
  const lines = text.split('\\n').filter(function (l) { return l.length > 0; });
  if (lines.length < 2) return false; // a header line + at least one record line
  let header;
  try {
    header = JSON.parse(lines[0]);
  } catch {
    return false;
  }
  if (!header || header.encrypted !== true) return false;
  for (let i = 1; i < lines.length; i++) {
    let rec;
    try {
      rec = JSON.parse(lines[i]);
    } catch {
      return false;
    }
    if (!rec || rec.encrypted !== true || !isTranscriptEnvelopeString(rec.body)) return false;
  }
  return true;
}

async function defaultVerifyPhoenixToken(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return null;
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base) return null;
  let res;
  try {
    res = await fetch(base + '/api/v1/auth/me', {
      method: 'GET',
      headers: { Authorization: 'Bearer ' + presented },
    });
  } catch {
    return null;
  }
  if (!res.ok) return null;
  let body;
  try {
    body = await res.json();
  } catch {
    return null;
  }
  if (!body || typeof body.userId !== 'string' || !body.userId) return null;
  return { userId: body.userId, email: typeof body.email === 'string' ? body.email : '' };
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'private, no-store',
    },
  });
}
`;
}
