import * as path from 'path';
import {
  getBrowserRuntimeDir as getBrowserRuntimeDirRoot,
  readMeta,
  writeMeta,
  updateMeta,
} from '../state.js';
import { getConfigValue } from '../device-config.js';
import type { BrowserProfileConfig } from '../types.js';
import type { BrowserProfile } from './types.js';
import { findBrowserPath, findFirstInstalledBrowser, isPortInUse } from './chrome.js';
import { DEFAULT_VIEWPORT } from './devices.js';

export type { BrowserProfile } from './types.js';

export const DEFAULT_BROWSER_PROFILE_NAME = 'default';

/**
 * True for a profile whose contents only make sense on THIS machine, so it must
 * live in the per-machine doc rather than the fleet-synced agents.yaml.
 *
 * The auto-detected `default` always qualifies: it is generated by probing local
 * browser installs and a free local port, so its `binary:` is an absolute path
 * for one OS. Shared fleet-wide it caused a permanent rewrite loop — a macOS box
 * wrote `/Applications/...`, a Linux box rewrote `/usr/bin/chromium-browser`,
 * each on every `agents browser start`.
 *
 * As of RUSH-2716 it is not the only one: EVERY newly created profile is
 * machine-local unless the caller explicitly asks for the fleet-synced store
 * (`createProfile(p, { fleet: true })` / `--fleet`). See {@link createProfile}.
 * This predicate is what keeps an existing `default` that an older version wrote
 * into central from being written back there by {@link updateProfile}.
 */
function isMachineLocalProfile(name: string): boolean {
  return name === DEFAULT_BROWSER_PROFILE_NAME;
}

/**
 * Where a profile is stored, and therefore who sees it:
 *   - `local` — this machine's `devices/<machine>/agents.yaml` (`deviceBrowser`)
 *   - `fleet` — the synced `~/.agents/agents.yaml` (`browser`), visible on every box
 */
export type ProfileScope = 'local' | 'fleet';

/** A profile plus the store it actually lives in. */
export interface ScopedBrowserProfile {
  profile: BrowserProfile;
  scope: ProfileScope;
}

/**
 * The device-local configured default profile name (set via
 * `agents browser profiles set-default`), or undefined when unset. When set, it
 * is the profile `agents browser start` resolves to for BOTH the no-`--profile`
 * path and an explicit `--profile default`. Stored as this machine's
 * `browser.profile` device-config key (the per-device doc's `config:` block —
 * see lib/device-config.ts).
 */
export function getConfiguredDefaultProfileName(): string | undefined {
  return (getConfigValue('browser.profile').value as string | undefined) || undefined;
}

export function getBrowserRuntimeDir(): string {
  return getBrowserRuntimeDirRoot();
}

export function getProfileRuntimeDir(name: string): string {
  return path.join(getBrowserRuntimeDir(), name);
}

/**
 * Default destination for browser downloads for a profile. Set browser-global at
 * connect time (see BrowserService), so downloads land here even when the agent
 * never calls `browser download --path`. Keyed by the same composite name as the
 * runtime dir, so every profile is one self-contained tree.
 */
export function getProfileDownloadsDir(name: string): string {
  return path.join(getProfileRuntimeDir(name), 'downloads');
}

/**
 * Per-profile directory for a task's captured artifacts (screenshots, PDFs,
 * recordings). Replaces the legacy global `browser/sessions/<task>/` root — the
 * one-shot migration in migrate.ts folds old captures into here.
 */
export function getProfileSessionsDir(name: string, task: string): string {
  return path.join(getProfileRuntimeDir(name), 'sessions', task);
}

function configToProfile(name: string, config: BrowserProfileConfig): BrowserProfile {
  validateRemoteBrowserBinaries(config);
  return {
    name,
    description: config.description,
    browser: config.browser,
    binary: config.binary,
    electron: config.electron,
    targetFilter: config.targetFilter,
    endpoints: config.endpoints,
    defaultEndpoint: config.defaultEndpoint,
    chrome: config.chrome,
    secrets: config.secrets,
    viewport: config.viewport,
    logDir: config.logDir,
    logHost: config.logHost,
  };
}

function profileToConfig(profile: BrowserProfile): BrowserProfileConfig {
  validateRemoteBrowserBinaries(profile);
  const config: BrowserProfileConfig = {
    browser: profile.browser,
    endpoints: profile.endpoints,
  };
  if (profile.description) config.description = profile.description;
  if (profile.binary) config.binary = profile.binary;
  if (profile.electron) config.electron = profile.electron;
  if (profile.targetFilter) config.targetFilter = profile.targetFilter;
  if (profile.defaultEndpoint) config.defaultEndpoint = profile.defaultEndpoint;
  if (profile.chrome) config.chrome = profile.chrome;
  if (profile.secrets) config.secrets = profile.secrets;
  if (profile.viewport) config.viewport = profile.viewport;
  if (profile.logDir) config.logDir = profile.logDir;
  if (profile.logHost) config.logHost = profile.logHost;
  return config;
}

/**
 * Every profile visible on this machine: the fleet-shared ones plus this
 * machine's own. A machine-local entry WINS on a name collision — it was written
 * by this box for this box, whereas the shared copy may carry another OS's
 * binary path (that mismatch is exactly why `default` moved local).
 */
function allProfileConfigs(): Record<string, BrowserProfileConfig> {
  const meta = readMeta();
  return { ...meta.browser, ...meta.deviceBrowser };
}

export async function listProfiles(): Promise<BrowserProfile[]> {
  const configs = allProfileConfigs();
  return Object.entries(configs).map(([name, config]) => configToProfile(name, config));
}

/**
 * Every visible profile paired with the store it lives in. Same precedence as
 * {@link listProfiles} — a machine-local entry wins a name collision, so a name
 * present in both maps reports `local`, which is the copy that is actually used.
 */
export async function listProfilesWithScope(): Promise<ScopedBrowserProfile[]> {
  const meta = readMeta();
  const local = meta.deviceBrowser ?? {};
  return Object.entries(allProfileConfigs()).map(([name, config]) => ({
    profile: configToProfile(name, config),
    scope: (local[name] ? 'local' : 'fleet') as ProfileScope,
  }));
}

export async function getProfile(name: string): Promise<BrowserProfile | null> {
  const config = allProfileConfigs()[name];
  if (!config) return null;
  return configToProfile(name, config);
}

/**
 * True when `profile` can actually launch or attach on THIS machine.
 *
 * A remote (`ssh://`) profile runs its browser on the far host, so a local
 * binary check doesn't apply — assume launchable. A local profile must have its
 * configured browser/binary present on disk here; a `default` profile
 * auto-created on a different OS (e.g. a macOS Chrome path reused on Linux — the
 * "Custom binary not found" failure) fails this check so the caller re-detects
 * for the current machine.
 */
export function isProfileLaunchableHere(profile: BrowserProfile): boolean {
  const remote = Object.values(getEndpointPresets(profile)).some((preset) =>
    preset.target.startsWith('ssh://')
  );
  if (remote) return true;
  try {
    findBrowserPath(profile.browser, profile.binary);
    return true;
  } catch {
    return false;
  }
}

/**
 * Resolve the profile `agents browser start` uses when no `--profile` is given.
 *
 * Order: (1) the device-local configured default (`agents browser profiles
 * set-default <name>`) when it names an existing profile that can launch here;
 * (2) an existing `default` profile that can launch here; (3) auto-pick the
 * first installed Chromium-family browser per the platform priority list in
 * chrome.ts (macOS: chrome > brave > edge > chromium > comet > arc; Linux: chrome >
 * chromium > brave > edge; Windows: edge > chrome > brave > comet) and pin a
 * `default` profile to it. Throws an actionable error if none of those binaries
 * are installed.
 *
 * "Can launch here" matters because `agents.yaml` syncs across the fleet: a
 * `default` auto-created on macOS carries a `/Applications/...` binary path that
 * doesn't exist on a Linux box. Rather than hand that broken profile back (the
 * top browser roadblock — "Custom binary not found"), we re-detect and
 * regenerate the `default` for this machine. A configured or existing default
 * that no longer exists, or can't launch here, warns and falls through — never a
 * hard fail.
 */
export async function ensureDefaultBrowserProfile(): Promise<BrowserProfile> {
  const configured = getConfiguredDefaultProfileName();
  if (configured) {
    const chosen = await getProfile(configured);
    if (chosen && isProfileLaunchableHere(chosen)) return chosen;
    console.warn(
      chosen
        ? `warning: configured default browser profile "${configured}" can't launch on this ` +
          `machine (its browser/binary isn't installed here); falling back to auto-detect. ` +
          `Fix with: agents browser profiles set-default <name>  (or --unset)`
        : `warning: configured default browser profile "${configured}" no longer exists; ` +
          `falling back to auto-detect. Fix with: agents browser profiles set-default <name>  (or --unset)`
    );
  }

  const existing = await getProfile(DEFAULT_BROWSER_PROFILE_NAME);
  if (existing && isProfileLaunchableHere(existing)) return existing;

  const detected = findFirstInstalledBrowser();
  if (!detected) {
    throw new Error(
      'No supported browser found. Install one of: Chrome, Brave, Edge, Chromium, Comet, or Arc, ' +
      'then re-run `agents browser start`. Or create a profile explicitly with ' +
      '`agents browser profiles create <name> --browser <chrome|comet|chromium|brave|edge|arc|custom>`. ' +
      'Note: Safari and Firefox are not supported — agents browser drives over the ' +
      'Chrome DevTools Protocol, which they don\'t implement.'
    );
  }

  const freePort = await findFreeProfilePort();
  const profile: BrowserProfile = {
    name: DEFAULT_BROWSER_PROFILE_NAME,
    description: `Auto-detected ${detected.browserType} profile`,
    browser: detected.browserType,
    binary: detected.binary,
    endpoints: [`cdp://127.0.0.1:${freePort}`],
    viewport: {
      width: DEFAULT_VIEWPORT.width,
      height: DEFAULT_VIEWPORT.height,
    },
  };
  // A stale `default` (auto-created on another OS, unlaunchable here) is
  // regenerated in place; otherwise this is the first-run create.
  if (existing) {
    await updateProfile(profile);
  } else {
    await createProfile(profile);
  }
  return profile;
}

/**
 * Compute the LOCAL port a profile will occupy at runtime:
 *   - `cdp://127.0.0.1:N` → N (we listen on N directly)
 *   - `ssh://host?port=N` → N (the SSH tunnel binds local N → remote N now)
 *   - `ws[s]://`, `http[s]://` → undefined (we don't claim a local port)
 *
 * This is what callers should compare to detect collisions; the (host,
 * port) tuple is no longer enough because SSH profiles do compete with
 * cdp:// profiles for local ports under the new tunnel scheme.
 */
export function effectiveLocalPort(profile: BrowserProfile): number | undefined {
  const presets = getEndpointPresets(profile);
  const firstName = profile.defaultEndpoint && presets[profile.defaultEndpoint]
    ? profile.defaultEndpoint
    : Object.keys(presets)[0];
  if (!firstName) return undefined;
  const target = presets[firstName].target;
  let url: URL;
  try { url = new URL(target); } catch { return undefined; }
  if (url.protocol !== 'cdp:' && url.protocol !== 'ssh:') return undefined;
  return parseEndpointUrl(target)?.port;
}

/**
 * Find a port in 9222–9399 that is not already claimed by ANY existing
 * profile (cdp:// or ssh://) and is not in use by any OS process. The
 * SSH change to bind locally on `?port=N` means we no longer get to
 * skip remote profiles in this scan.
 */
export async function findFreeProfilePort(): Promise<number> {
  const profiles = await listProfiles();
  const usedByProfile = new Set<number>();
  for (const p of profiles) {
    const port = effectiveLocalPort(p);
    if (port !== undefined) usedByProfile.add(port);
  }

  for (let port = 9222; port <= 9399; port++) {
    if (usedByProfile.has(port)) continue;
    // Platform-aware bound-port probe (lsof on POSIX, netstat on Windows).
    // The old inline lsof call threw ENOENT on Windows — where lsof doesn't
    // exist — so EVERY port scanned as "free", including one an already-
    // running browser was listening on (typically 9222), and the new profile
    // would silently attach to that browser instead of launching its own.
    if (!isPortInUse(port)) return port;
  }

  throw new Error('No available ports in range 9222-9399');
}

function validateRemoteBrowserBinaries(
  profile: Pick<BrowserProfileConfig, 'binary' | 'endpoints'>
): void {
  if (!hasSshEndpoint(profile.endpoints)) return;
  validateRemoteBrowserBinary(profile.binary);
  if (!Array.isArray(profile.endpoints)) {
    for (const preset of Object.values(profile.endpoints)) {
      validateRemoteBrowserBinary(preset.binary);
    }
  }
}

function validateRemoteBrowserBinary(binary: string | undefined): void {
  if (!binary) return;
  if (/[\0\r\n;&|`$<>]/.test(binary)) {
    throw new Error(
      `Remote browser binary contains shell metacharacters: ${binary}`
    );
  }
}

function hasSshEndpoint(endpoints: BrowserProfileConfig['endpoints']): boolean {
  const targets = Array.isArray(endpoints)
    ? endpoints
    : Object.values(endpoints).map((preset) => preset.target);
  return targets.some((target) => {
    try {
      return new URL(target).protocol === 'ssh:';
    } catch {
      return false;
    }
  });
}

/**
 * Create a profile. **It lands in this machine's own store by default** — pass
 * `{ fleet: true }` (the CLI's `--fleet`) to put it in the synced `agents.yaml`
 * where every box will see it.
 *
 * Local-by-default is the RUSH-2716 fix. A profile is a local browser install
 * (`binary:` is an absolute path for one OS) bound to a locally chosen free port,
 * so the fleet-synced copy is wrong on every other machine to begin with; and
 * because agents mint throwaway profiles freely, every ad-hoc one was syncing to
 * every machine as junk that nothing cleaned up (`agents browser profiles prune`
 * is the other half of that fix). Opting in with `--fleet` is for a profile that
 * really is fleet config — a remote `ssh://` endpoint, or a named profile whose
 * shape you want on every box.
 *
 * Existing profiles are NOT migrated: this only decides where a NEW entry is
 * written, so a fleet profile created before this change keeps syncing.
 */
export async function createProfile(
  profile: BrowserProfile,
  opts: { fleet?: boolean } = {}
): Promise<void> {
  const meta = readMeta();
  const existingConfigs = allProfileConfigs();
  if (existingConfigs[profile.name]) {
    throw new Error(`Profile "${profile.name}" already exists`);
  }

  // Collision check. Every CDP/SSH profile ends up listening on (or
  // tunneling to) the same LOCAL port number as the one configured in the
  // endpoint URL — SSH profiles now reuse `?port=N` locally so we no
  // longer need to scope by host. Two profiles that would need the same
  // local port can't both run at the same time.
  const newLocal = effectiveLocalPort(profile);
  if (newLocal !== undefined) {
    for (const [existingName, existingConfig] of Object.entries(existingConfigs)) {
      const existingProfile = configToProfile(existingName, existingConfig);
      const existingLocal = effectiveLocalPort(existingProfile);
      if (existingLocal === newLocal) {
        throw new Error(
          `Local port ${newLocal} is already used by profile "${existingName}". ` +
            `Each profile must own a unique local port (SSH tunnels now bind ` +
            `to their configured port locally too). Pick a different port.`
        );
      }
    }
  }

  // Resolve the browser binary at create time. Fails fast with an actionable
  // error ("Comet not installed at /Applications/Comet.app") rather than
  // deferring the failure to the first task. `findBrowserPath` short-circuits
  // for browser=custom without a binary by throwing — same outcome.
  //
  // Skip for SSH profiles: the browser binary lives on the remote host, so a
  // local lookup would validate the wrong machine. The remote launcher resolves
  // it at connect time.
  if (!hasSshEndpoint(profile.endpoints)) {
    findBrowserPath(profile.browser, profile.binary);
  }

  const config = profileToConfig(profile);
  // Machine-local unless the caller explicitly asked for the fleet store. The
  // auto `default` is always local regardless of what a caller passes — its
  // binary path and port are this box's, and fleet-syncing it is the rewrite
  // loop RUSH-2161 fixed.
  if (!opts.fleet || isMachineLocalProfile(profile.name)) {
    updateMeta((m) => ({ ...m, deviceBrowser: { ...m.deviceBrowser, [profile.name]: config } }));
    return;
  }
  updateMeta((m) => ({ ...m, browser: { ...m.browser, [profile.name]: config } }));
}

export async function updateProfile(profile: BrowserProfile): Promise<void> {
  const meta = readMeta();
  const local = meta.deviceBrowser?.[profile.name];
  if (!local && !meta.browser?.[profile.name]) {
    throw new Error(`Profile "${profile.name}" does not exist`);
  }

  const config = profileToConfig(profile);
  // A profile that already lives machine-locally stays there; so does the auto
  // `default`, whose binary path and port are specific to this machine.
  if (local || isMachineLocalProfile(profile.name)) {
    updateMeta((m) => ({ ...m, deviceBrowser: { ...m.deviceBrowser, [profile.name]: config } }));
    return;
  }
  updateMeta((m) => ({ ...m, browser: { ...m.browser, [profile.name]: config } }));
}

export async function deleteProfile(name: string): Promise<void> {
  const meta = readMeta();
  const isLocal = !!meta.deviceBrowser?.[name];
  if (!isLocal && !meta.browser?.[name]) {
    throw new Error(`Profile "${name}" does not exist`);
  }

  updateMeta((m) => {
    if (isLocal) {
      const next = { ...m.deviceBrowser };
      delete next[name];
      return { ...m, deviceBrowser: Object.keys(next).length > 0 ? next : undefined };
    }
    const next = { ...m.browser };
    delete next[name];
    return { ...m, browser: Object.keys(next).length > 0 ? next : undefined };
  });
}

/** Widest NAME column we will grow to before truncating instead. */
const MAX_NAME_COLUMN = 28;

/**
 * Pad `text` to exactly `width` visible characters, truncating with an ellipsis
 * when it does not fit. `padEnd` alone does NOT bound a long value — it returns
 * the string unchanged when it already exceeds the width, which is what pushed
 * every later column out of alignment on a name longer than 20 characters
 * (RUSH-2710). Every column here goes through this, never a bare `padEnd`.
 */
export function padColumn(text: string, width: number): string {
  if (width <= 0) return '';
  if (text.length <= width) return text.padEnd(width);
  if (width === 1) return '…';
  return text.slice(0, width - 1) + '…';
}

/**
 * Render the `agents browser profiles list` table.
 *
 * Pure (no fs, no config reads) so the alignment and the default-marking rules
 * are unit-testable without a configured machine.
 *
 * Two things used to be called "default" in this listing with no way to tell
 * them apart (RUSH-2710): the profile literally NAMED `default` (the
 * auto-detected one), and whichever profile this machine resolves a bare
 * `agents browser start` to (`agents config set browser.profile <name>`). They
 * are frequently different profiles. Now only the second is a marker — a `*` in
 * a leading column, explained by a legend line — so the name column carries just
 * the name and `default` in it always means the profile of that name.
 *
 * The SCOPE column is the RUSH-2716 companion: it says whether an entry lives on
 * this machine only (`local`) or in the fleet-synced `agents.yaml` (`fleet`), so
 * "why does this box have a profile I never made here?" is answerable at a
 * glance.
 */
export function formatProfilesTable(
  rows: ScopedBrowserProfile[],
  configuredDefault?: string
): string[] {
  const cells = rows.map(({ profile, scope }) => {
    const presets = getEndpointPresets(profile);
    const endpoints = Object.entries(presets)
      .map(([name, ep]) => (name.startsWith('endpoint-') ? ep.target : `${name}=${ep.target}`))
      .join(', ');
    return {
      marker: profile.name === configuredDefault ? '*' : ' ',
      name: profile.name,
      browser: profile.browser || '-',
      scope,
      description: profile.description ?? '',
      endpoints,
    };
  });

  const nameWidth = Math.min(
    MAX_NAME_COLUMN,
    Math.max('NAME'.length, ...cells.map((c) => c.name.length))
  );
  const browserWidth = Math.max('BROWSER'.length, ...cells.map((c) => c.browser.length));
  // 'local' / 'fleet' are both 5 chars, so the header is the widest value.
  const scopeWidth = 'SCOPE'.length;
  const hasDescriptions = cells.some((c) => c.description);
  const descWidth = hasDescriptions
    ? Math.min(36, Math.max('DESCRIPTION'.length, ...cells.map((c) => c.description.length)))
    : 0;

  const row = (
    marker: string,
    name: string,
    browser: string,
    scope: string,
    desc: string,
    endpoints: string
  ): string =>
    `${marker} ` +
    padColumn(name, nameWidth) + '  ' +
    padColumn(browser, browserWidth) + '  ' +
    padColumn(scope, scopeWidth) + '  ' +
    (hasDescriptions ? padColumn(desc, descWidth) + '  ' : '') +
    endpoints;

  const header = row(' ', 'NAME', 'BROWSER', 'SCOPE', 'DESCRIPTION', 'ENDPOINTS');
  const lines = [header, '-'.repeat(header.length)];
  for (const c of cells) {
    lines.push(row(c.marker, c.name, c.browser, c.scope, c.description, c.endpoints));
  }
  if (configuredDefault) {
    lines.push('');
    lines.push(
      `* = this machine's default profile (${configuredDefault}) — what a bare \`agents browser start\` uses.`
    );
  }
  lines.push(
    hasFleetRow(rows)
      ? 'scope: local = this machine only · fleet = synced to every machine (agents.yaml).'
      : 'scope: local = this machine only. Create a synced one with: agents browser profiles create <name> --fleet'
  );
  return lines;
}

function hasFleetRow(rows: ScopedBrowserProfile[]): boolean {
  return rows.some((r) => r.scope === 'fleet');
}

/**
 * Resolve a profile's endpoint presets into a normalized map regardless of
 * whether the YAML uses the legacy `string[]` shape or the new map shape.
 * The legacy entries get auto-named `endpoint-0`, `endpoint-1`, ... .
 */
export function getEndpointPresets(
  profile: BrowserProfile
): Record<string, import('./types.js').EndpointPreset> {
  if (Array.isArray(profile.endpoints)) {
    const out: Record<string, import('./types.js').EndpointPreset> = {};
    profile.endpoints.forEach((target, i) => {
      out[`endpoint-${i}`] = { target };
    });
    return out;
  }
  return profile.endpoints;
}

/**
 * Pick the endpoint preset to use. Order:
 *   1. Explicit name passed in (errors if unknown)
 *   2. `profile.defaultEndpoint` if set
 *   3. First entry (preserves legacy string[] behavior)
 *
 * Returns the resolved name + the preset (with per-endpoint overrides
 * already applied to binary / targetFilter), so callers don't have to
 * remember the precedence rules.
 */
export function resolveEndpoint(
  profile: BrowserProfile,
  endpointName?: string
): { name: string; target: string; binary?: string; targetFilter?: string } {
  const presets = getEndpointPresets(profile);
  const names = Object.keys(presets);
  if (names.length === 0) {
    throw new Error(`Profile "${profile.name}" has no endpoints configured`);
  }

  let chosenName: string;
  if (endpointName) {
    if (!presets[endpointName]) {
      throw new Error(
        `Endpoint "${endpointName}" not found on profile "${profile.name}". ` +
          `Available: ${names.join(', ')}`
      );
    }
    chosenName = endpointName;
  } else if (profile.defaultEndpoint && presets[profile.defaultEndpoint]) {
    chosenName = profile.defaultEndpoint;
  } else {
    chosenName = names[0];
  }

  const preset = presets[chosenName];
  return {
    name: chosenName,
    target: preset.target,
    binary: preset.binary ?? profile.binary,
    targetFilter: preset.targetFilter ?? profile.targetFilter,
  };
}

/**
 * Extract the (host, port) pair intended by the profile's default endpoint.
 * Returns undefined for endpoint shapes that don't carry a port (e.g. ws:// without one).
 *
 * Ports are scoped by host: a `cdp://127.0.0.1:9222` profile (local Chrome on
 * this machine) and an `ssh://remote-host:9222` profile (Comet on a remote
 * host) point at different physical ports — the host disambiguates them.
 *
 * Accepts both `scheme://host:port` and `scheme://host?port=N` shapes (the
 * latter is the documented form in `types.ts` for `ssh://`). Without this,
 * `ssh://remote-host?port=18805` would silently fall back to 9222 and every
 * `?port=`-style SSH profile would collide on creation.
 */
export function extractConfiguredEndpoint(
  profile: BrowserProfile
): { host: string; port: number } | undefined {
  const presets = getEndpointPresets(profile);
  const firstName = profile.defaultEndpoint && presets[profile.defaultEndpoint]
    ? profile.defaultEndpoint
    : Object.keys(presets)[0];
  if (!firstName) return undefined;
  return parseEndpointUrl(presets[firstName].target);
}

/**
 * Shared endpoint parser used by both the collision-detection code path and
 * the connection drivers. Returning a single normalized `(host, port)` here
 * keeps `extractConfiguredEndpoint` and the SSH driver from drifting on URL
 * conventions (which is how `?port=N` ended up being silently ignored).
 */
export function parseEndpointUrl(
  endpoint: string
): { host: string; port: number } | undefined {
  let url: URL;
  try {
    url = new URL(endpoint);
  } catch {
    return undefined;
  }
  const host = normalizeHost(url.hostname, url.protocol);
  if (!host) return undefined;
  const port = extractPortFromUrl(url);
  if (port !== undefined) return { host, port };
  // SSH endpoints tunnel to a remote port AND bind that same port locally,
  // so they do "own" a local port — the host-scoped collision check used
  // to disagree, but we want the local-port-scoped semantics now.
  if (url.protocol === 'cdp:' || url.protocol === 'ssh:') return { host, port: 9222 };
  return undefined;
}

function extractPortFromUrl(url: URL): number | undefined {
  if (url.port) {
    const n = parseInt(url.port, 10);
    if (Number.isFinite(n)) return n;
  }
  // `scheme://host?port=N` — the form documented for SSH endpoints in
  // `types.ts`. WHATWG URL parsing surfaces it via searchParams only.
  const qp = url.searchParams.get('port');
  if (qp) {
    const n = parseInt(qp, 10);
    if (Number.isFinite(n)) return n;
  }
  return undefined;
}

/**
 * Extract the port intended by the profile's default endpoint.
 * Returns undefined for endpoint shapes that don't carry a port (e.g. ws:// without one).
 *
 * Note: this loses the host dimension — for collision detection use
 * `extractConfiguredEndpoint` instead, which returns the (host, port) pair.
 */
export function extractConfiguredPort(profile: BrowserProfile): number | undefined {
  return extractConfiguredEndpoint(profile)?.port;
}

function normalizeHost(hostname: string, protocol: string): string | undefined {
  if (!hostname) {
    // cdp:// and ssh:// without an explicit host imply localhost.
    if (protocol === 'cdp:' || protocol === 'ssh:') return '127.0.0.1';
    return undefined;
  }
  if (hostname === 'localhost') return '127.0.0.1';
  return hostname;
}

export function isLocalHost(host: string): boolean {
  return host === '127.0.0.1' || host === 'localhost' || host === '::1';
}
