// The Cloudflare Worker that fronts the R2 traces bucket.
//
// SECURITY: unlike agents-share, there is NO public GET path here. Every route
// — PUT and GET — requires a Phoenix bearer. The caller must be the record's
// owner (path prefix == verified userId). A missing bearer → 401; a wrong
// owner → 403; public cache headers are NEVER emitted.
//
// Routes (all require Phoenix bearer + userId owner match):
//   PUT  /<userId>/<device>/index.json            — per-device stats shard
//   PUT  /<userId>/<device>/sessions/<id>.json    — per-session SessionDetail
//   GET  /<userId>/...                            — returns the stored object
//   GET  /                                        — 200 description (no data)
//
// Emitted as a string so it compiles into dist/** and ships with no
// package.json#files change. `provisionTraces.ts` uploads this verbatim as an
// ES-module Worker with a BUCKET (R2) binding + a PHOENIX_ID_BASE secret.

/**
 * Render the traces Worker source. Pure — bindings are wired at deploy time.
 */
export function renderTracesWorkerScript(): string {
  return `// GENERATED by agents-cli agents traces — do not edit; edit
// src/lib/traces/worker-template.ts and re-provision.
export const hooks = {
  verifyPhoenixToken: defaultVerifyPhoenixToken,
};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname.replace(/^\\/+/, ''));

    if (!path) {
      return new Response(
        'agents traces — PUT /<userId>/<device>/index.json or sessions/<id>.json to upload; GET the same path to read. All routes require a Phoenix bearer.',
        { status: 200, headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'private, no-store' } },
      );
    }

    if (request.method === 'PUT') {
      return handlePut(request, env, path);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      return handleGet(request, env, path);
    }

    return json({ error: 'method not allowed' }, 405);
  },
};

async function handlePut(request, env, path) {
  const auth = await authorizeWrite(request, env);
  if (auth.error) return auth.error;

  const segments = path.split('/').filter(Boolean);
  const expected = auth.owner;
  if (!expected || segments[0] !== expected) {
    return json({ error: 'namespace mismatch', owner: expected }, 403);
  }

  const contentType = request.headers.get('content-type') || 'application/json; charset=utf-8';
  await env.BUCKET.put(path, request.body, {
    httpMetadata: { contentType },
    customMetadata: {
      owner: auth.owner,
      uploadedAt: new Date().toISOString(),
    },
  });

  const headers = new Headers();
  headers.set('cache-control', 'private, no-store');
  return new Response(JSON.stringify({ ok: true, key: path }), {
    status: 200,
    headers,
  });
}

async function handleGet(request, env, path) {
  const auth = await authorizeRead(request, env, path);
  if (auth.error) return auth.error;

  const object = await env.BUCKET.get(path);
  if (!object) return json({ error: 'not found' }, 404);

  const headers = new Headers(object.httpMetadata ?? {});
  headers.set('cache-control', 'private, no-store');
  return new Response(object.body, { headers });
}

// Require a Phoenix bearer that owns the path prefix.
async function authorizeRead(request, env, path) {
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (!claims) return { error: json({ error: 'unauthorized' }, 401) };
  const ownerId = path.split('/').filter(Boolean)[0] || '';
  if (!ownerId || ownerId !== claims.userId) {
    return { error: json({ error: 'forbidden' }, 403) };
  }
  return { claims };
}

// Two legitimate principals for writes: static WRITE_TOKEN first (BYO),
// otherwise Phoenix bearer. 401 when neither authenticates.
async function authorizeWrite(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return { error: json({ error: 'unauthorized' }, 401) };
  if (env.WRITE_TOKEN && safeEqual(presented, env.WRITE_TOKEN)) {
    return { kind: 'byo', owner: env.TRACES_NAMESPACE || 'byo' };
  }
  const claims = await hooks.verifyPhoenixToken(request, env);
  if (claims && typeof claims.userId === 'string' && claims.userId) {
    return { kind: 'phoenix', owner: claims.userId };
  }
  return { error: json({ error: 'unauthorized' }, 401) };
}

async function defaultVerifyPhoenixToken(request, env) {
  const presented = (request.headers.get('authorization') || '').replace(/^Bearer\\s+/i, '');
  if (!presented) return null;
  const base = typeof env.PHOENIX_ID_BASE === 'string' ? env.PHOENIX_ID_BASE.replace(/\\/+$/, '') : '';
  if (!base) return null;
  let res;
  try {
    res = await fetch(base + '/api/v1/auth/me', {
      method: 'GET',
      headers: { Authorization: 'Bearer ' + presented },
    });
  } catch {
    return null;
  }
  if (!res.ok) return null;
  let body;
  try {
    body = await res.json();
  } catch {
    return null;
  }
  if (!body || typeof body.userId !== 'string' || !body.userId) return null;
  return { userId: body.userId, email: typeof body.email === 'string' ? body.email : '' };
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'private, no-store',
    },
  });
}

// Constant-time comparison so timing attacks can't probe a static WRITE_TOKEN.
function safeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}
`;
}
